// Additional English -> Norwegian (bokmål) phrases used by the automatic page translator
// and by t(). Keys are matched case-insensitively against trimmed text.
const extraPhrasesNo = {
  // Login & auth
  "Staff Login": "Ansattinnlogging",
  "B2B Login": "B2B-innlogging",
  "Sign Up": "Registrer deg",
  "Sign In": "Logg inn",
  "Sign in to your account": "Logg inn på kontoen din",
  "Choose your access type below": "Velg innloggingstype nedenfor",
  "Email Address": "E-postadresse",
  "Email or Phone": "E-post eller telefon",
  "Password": "Passord",
  "Forgot?": "Glemt?",
  "Signing in...": "Logger inn...",
  "Creating Account...": "Oppretter konto...",
  "Create Account & Browse Catalog": "Opprett konto og bla i katalogen",
  "Continue with Google": "Fortsett med Google",
  "Sign in with Google": "Logg inn med Google",
  "Secure encrypted access portal": "Sikker, kryptert tilgangsportal",
  "Encrypted SSL Portal": "Kryptert SSL-portal",
  "Company Name": "Firmanavn",
  "Contact Person Name": "Kontaktpersonens navn",
  "Email": "E-post",
  "Phone": "Telefon",
  "Street Address": "Gateadresse",
  "City / Postal": "Sted / postnummer",
  "Authenticating...": "Autentiserer...",
  "Continue with this Google Account": "Fortsett med denne Google-kontoen",
  "Your Gmail / Google Email Address": "Din Gmail- / Google-e-postadresse",
  "Your Full Name / Business Name (Optional)": "Fullt navn / firmanavn (valgfritt)",
  "Enter your real Gmail account to connect and log in to the B2B portal.": "Skriv inn din Gmail-konto for å koble til og logge inn på B2B-portalen.",
  "Please enter your Gmail address": "Vennligst skriv inn Gmail-adressen din",
  "Could not retrieve email from Google": "Kunne ikke hente e-post fra Google",
  "Failed to fetch Google profile": "Kunne ikke hente Google-profil",
  "Invalid credentials": "Ugyldig brukernavn eller passord",
  "Login failed": "Innlogging mislyktes",
  "Login successful": "Innlogging vellykket",
  "Registration failed": "Registrering mislyktes",
  "Select Language": "Velg språk",
  "Language": "Språk",
  "English": "Engelsk",
  "Norsk": "Norsk",
  "Staff": "Ansatt",
  "Admin": "Administrator",
  "Manager": "Leder",
  "Cashier": "Kasserer",

  // Generic UI
  "Action": "Handling",
  "Actions": "Handlinger",
  "Add": "Legg til",
  "Add User": "Legg til bruker",
  "Assign": "Tildel",
  "Assigned": "Tildelt",
  "Approved": "Godkjent",
  "Back to List": "Tilbake til listen",
  "Back to Returns": "Tilbake til returer",
  "Back to Sales": "Tilbake til salg",
  "Cancel": "Avbryt",
  "Clear": "Tøm",
  "Close": "Lukk",
  "Created": "Opprettet",
  "Created By": "Opprettet av",
  "Del": "Slett",
  "Delete": "Slett",
  "Edit": "Rediger",
  "Remove": "Fjern",
  "Remove item": "Fjern vare",
  "Remove row": "Fjern rad",
  "Save": "Lagre",
  "Search": "Søk",
  "Loading...": "Laster...",
  "No Custom Logo": "Ingen egendefinert logo",
  "View Details": "Vis detaljer",
  "View Invoice": "Vis faktura",
  "View Profile & Orders": "Vis profil og bestillinger",
  "Website": "Nettsted",
  "Timestamp": "Tidspunkt",
  "Reason": "Årsak",
  "Item": "Vare",
  "Items Ordered": "Bestilte varer",
  "Quantity:": "Antall:",
  "Note:": "Merknad:",
  "Total:": "Totalt:",
  "Subtotal:": "Delsum:",
  "Tax:": "Avgift:",
  "Discount:": "Rabatt:",
  "Style:": "Stil:",
  "Care:": "Vask:",
  "Paper:": "Papir:",
  "Carton:": "Kartong:",
  "Company:": "Firma:",
  "Customer": "Kunde",
  "Customer (Optional)": "Kunde (valgfritt)",
  "Customer Info": "Kundeinformasjon",
  "Customer Source": "Kundekilde",
  "Customer Segments": "Kundesegmenter",
  "Active Account": "Aktiv konto",
  "Active Customers": "Aktive kunder",
  "Account Code:": "Kontokode:",
  "Alternate Phone": "Alternativ telefon",
  "Phone Number": "Telefonnummer",
  "Designation": "Stilling",
  "Designation / Role": "Stilling / rolle",
  "Title / Role": "Tittel / rolle",
  "Contact Name *": "Kontaktnavn *",
  "Contact Person:": "Kontaktperson:",
  "Stakeholders": "Interessenter",
  "Purchasing Director": "Innkjøpsdirektør",
  "Select User": "Velg bruker",
  "Search users...": "Søk etter brukere...",
  "No users found.": "Ingen brukere funnet.",
  "No sales found.": "Ingen salg funnet.",
  "No matching products found": "Ingen samsvarende produkter funnet",
  "Delete User": "Slett bruker",
  "User created successfully": "Bruker opprettet",
  "User updated successfully": "Bruker oppdatert",
  "User deleted successfully": "Bruker slettet",
  "Failed to fetch users": "Kunne ikke hente brukere",
  "Products": "Produkter",
  "Article": "Artikkel",
  "Article Product": "Artikkelprodukt",
  "Article Preview": "Forhåndsvisning av artikkel",
  "Article not found.": "Artikkel ikke funnet.",
  "Article Photo (Product Image)": "Artikkelbilde (produktbilde)",
  "Brand": "Merke",
  "Color / Code": "Farge / kode",
  "Condition": "Tilstand",
  "Condition Status": "Tilstandsstatus",
  "Size": "Størrelse",
  "Current Size": "Gjeldende størrelse",
  "Tol.": "Tol.",
  "Payment": "Betaling",
  "Payment Summary": "Betalingsoppsummering",
  "Process Date": "Behandlingsdato",
  "Processed By": "Behandlet av",
  "Sale Date": "Salgsdato",
  "Sales": "Salg",
  "Sales Receipt": "Salgskvittering",
  "Sales Receipt Invoice Ready": "Salgskvittering klar",
  "Sales already captured": "Salg allerede registrert",
  "Invoice": "Faktura",
  "Invoice Details": "Fakturadetaljer",
  "Invoice Number": "Fakturanummer",
  "Line Total": "Linjesum",
  "Transaction Meta": "Transaksjonsinfo",
  "Internal Remarks": "Interne merknader",
  "Inventory Note": "Lagernotat",
  "Notes / Remarks": "Notater / merknader",
  "Edit Remarks": "Rediger merknader",
  "Edit Record": "Rediger post",
  "Markup %": "Påslag %",
  "Agreed Contract Price": "Avtalt kontraktspris",
  "Contract Price": "Kontraktspris",
  "Discount (NOK)": "Rabatt (NOK)",
  "VAT / MVA 25% (NOK)": "MVA 25 % (NOK)",
  "Tax / MVA": "Avgift / MVA",
  "USD Price ($)": "USD-pris ($)",
  "Calculate from USD Invoice": "Beregn fra USD-faktura",
  "1 USD = NOK": "1 USD = NOK",
  "NOK - Norske Kroner (kr)": "NOK – Norske kroner (kr)",
  "USD - US Dollar ($)": "USD – amerikanske dollar ($)",
  "EUR - Euro (€)": "EUR – euro (€)",
  "Bank Card / POS Terminal": "Bankkort / betalingsterminal",
  "Card / POS Terminal": "Kort / betalingsterminal",
  "WhatsApp Pay": "WhatsApp Pay",
  "Walk-in Customer": "Gangkunde",
  "General Support / Walk-in": "Generell support / gangkunde",
  "POS & Sales Counter": "POS og salgsdisk",
  "Cart": "Handlekurv",
  "Cart Items": "Varer i handlekurv",
  "Cart is empty": "Handlekurven er tom",
  "+ Add to Cart": "+ Legg i handlekurv",
  "Increase quantity": "Øk antall",
  "Decrease quantity": "Reduser antall",
  "Enter quantity": "Skriv inn antall",
  "Total Cart Value:": "Total handlekurvverdi:",
  "Create Sale": "Opprett salg",
  "Print Receipt": "Skriv ut kvittering",
  "Edit Sale": "Rediger salg",
  "Edit Sale Transaction": "Rediger salgstransaksjon",
  "Delete Sale": "Slett salg",
  "Delete Sale Transaction": "Slett salgstransaksjon",
  "Sale completed successfully!": "Salget er fullført!",
  "Sale deleted successfully": "Salg slettet",
  "Sale updated successfully": "Salg oppdatert",
  "Sale not found": "Salg ikke funnet",
  "Failed to fetch sale": "Kunne ikke hente salg",
  "Failed to fetch sales": "Kunne ikke hente salg",
  "Failed to fetch sale setup data": "Kunne ikke hente salgsoppsett",
  "Failed to load sale record": "Kunne ikke laste salgspost",
  "Loading sale data...": "Laster salgsdata...",
  "Process in-store sales, select customer, scan barcodes, and generate instant receipt invoices.": "Behandle butikksalg, velg kunde, skann strekkoder og lag kvitteringer umiddelbart.",
  "Search product by name, SKU barcode or style...": "Søk produkt etter navn, SKU, strekkode eller stil...",
  "Search invoice, customer, or product...": "Søk faktura, kunde eller produkt...",
  "Search by product, SKU, or reason...": "Søk etter produkt, SKU eller årsak...",
  "Special delivery notes or terms...": "Spesielle leveringsnotater eller vilkår...",
  "PO number, department, internal memo...": "Bestillingsnr., avdeling, internt notat...",
  "Enter delivery address...": "Skriv inn leveringsadresse...",
  "Add any internal notes or remarks about this transaction...": "Legg til interne notater om denne transaksjonen...",

  // Returns
  "Product Returns": "Produktreturer",
  "Return Details": "Returdetaljer",
  "Return Reason": "Returårsak",
  "Edit Return": "Rediger retur",
  "Edit Return Record": "Rediger returpost",
  "Delete Return": "Slett retur",
  "Delete Return Record": "Slett returpost",
  "Return processed successfully": "Retur behandlet",
  "Return record deleted successfully": "Returpost slettet",
  "Return record updated successfully": "Returpost oppdatert",
  "Failed to load returns": "Kunne ikke laste returer",
  "Failed to load return details": "Kunne ikke laste returdetaljer",
  "Failed to load return record": "Kunne ikke laste returpost",
  "Loading return data...": "Laster returdata...",
  "Loading return details...": "Laster returdetaljer...",
  "Handle product returns, track item condition, and update stock levels.": "Håndter produktreturer, spor varens tilstand og oppdater lagernivåer.",
  "Why is this being returned?": "Hvorfor returneres dette?",
  "Update the reason for this return...": "Oppdater årsaken til denne returen...",
  "Search returns...": "Søk i returer...",
  "Usable (Restore Stock)": "Brukbar (gjenopprett lager)",
  "Usable (Stock Restored)": "Brukbar (lager gjenopprettet)",
  "Damaged (No Stock Restoration)": "Skadet (ingen lagergjenoppretting)",
  "Damaged (No Stock Restore)": "Skadet (ingen lagergjenoppretting)",
  "Refurbished": "Oppusset",
  "Note: Changing status to/from \"Usable\" will automatically adjust current stock.": "Merk: Endring av status til/fra «Brukbar» justerer lagerbeholdningen automatisk.",
  "Recent Returns": "Siste returer",

  // Stock / barcode
  "Barcode and Quantity are required": "Strekkode og antall er påkrevd",
  "Barcode image downloaded!": "Strekkodebilde lastet ned!",
  "Barcode number copied to clipboard!": "Strekkodenummer kopiert til utklippstavlen!",
  "Barcode scanned successfully": "Strekkode skannet",
  "Could not download image": "Kunne ikke laste ned bildet",
  "Failed to load barcode details": "Kunne ikke laste strekkodedetaljer",
  "No barcode available": "Ingen strekkode tilgjengelig",
  "Master Barcode:": "Hovedstrekkode:",
  "Unit Barcode": "Enhetsstrekkode",
  "UNIT BARCODE": "ENHETSSTREKKODE",
  "SKU / Article": "SKU / artikkel",
  "SKU CODE": "SKU-KODE",
  "Scan Garment Tag Barcode": "Skann strekkode på plaggets merkelapp",
  "Scan manufacturer barcode...": "Skann produsentens strekkode...",
  "Scan or enter barcode": "Skann eller skriv inn strekkode",
  "Point camera toward barcode": "Pek kameraet mot strekkoden",
  "Click any size to preview barcode": "Klikk på en størrelse for å se strekkoden",
  "Live barcode metadata & catalog specs": "Strekkodedata og katalogspesifikasjoner",
  "Generating barcode graphics...": "Genererer strekkodegrafikk...",
  "⚠️ Pending Stock Out Fulfillment": "⚠️ Venter på utlevering (Stock Out)",
  "Quantity": "Antall",
  "Stock": "Lager",

  // Export / downloads / documents
  "Download Excel (+ Barcodes)": "Last ned Excel (+ strekkoder)",
  "Download Excel Sheet": "Last ned Excel-ark",
  "Excel file downloaded successfully!": "Excel-filen er lastet ned!",
  "Failed to export Excel file": "Kunne ikke eksportere Excel-fil",
  "Generating Excel sheet with barcode images...": "Genererer Excel-ark med strekkodebilder...",
  "Generating Excel sheet with embedded barcodes...": "Genererer Excel-ark med innebygde strekkoder...",
  "for embedded barcode spreadsheets.": "for regneark med innebygde strekkoder.",
  "Export & Print Options:": "Eksport- og utskriftsvalg:",
  "Export GDPR Data": "Eksporter GDPR-data",
  "Failed to export GDPR data": "Kunne ikke eksportere GDPR-data",
  "Failed to anonymize customer": "Kunne ikke anonymisere kunden",
  "Export Vector (.svg)": "Eksporter vektor (.svg)",
  "Vector (.svg)": "Vektor (.svg)",
  "Vector Graphics (.svg)": "Vektorgrafikk (.svg)",
  "CAD (.dxf)": "CAD (.dxf)",
  "AutoCAD DXF (.dxf)": "AutoCAD DXF (.dxf)",
  "Mixed Carton Sticker": "Klistremerke for blandet kartong",
  "Print All Sizes": "Skriv ut alle størrelser",
  "Print Size Chart": "Skriv ut størrelsestabell",
  "Close Size Chart": "Lukk størrelsestabell",
  "View exact size chart & measurements": "Se nøyaktig størrelsestabell og mål",
  "Download Delivery Note PDF": "Last ned pakkseddel (PDF)",
  "Delivery Note PDF downloaded!": "Pakkseddel (PDF) lastet ned!",
  "Delivery Note Printable PDF": "Pakkseddel som utskriftsvennlig PDF",
  "Failed to generate Delivery Note PDF": "Kunne ikke generere pakkseddel (PDF)",
  "EHF XML": "EHF XML",
  "EHF Pakkeseddel 3.0 XML downloaded!": "EHF Pakkeseddel 3.0 XML lastet ned!",
  "Failed to download EHF XML": "Kunne ikke laste ned EHF XML",
  "Generated Electronic XML Payload:": "Generert elektronisk XML-innhold:",
  "cXML Payload copied to clipboard!": "cXML-innhold kopiert til utklippstavlen!",
  "Official Nordic Prowear ERP Packing Label": "Offisiell Nordic Prowear ERP-pakkeetikett",
  "Official Nordic Prowear ERP Packing Manifest": "Offisiell Nordic Prowear ERP-pakkeliste",
  "Corporate B2B Invoice": "B2B-firmafaktura",
  "QR Manifest": "QR-pakkeliste",
  "Dispatched By (Nordic Prowear Warehouse):": "Sendt av (Nordic Prowear lager):",
  "Received & Signed By Customer:": "Mottatt og signert av kunde:",
  "RECIPIENT CUSTOMER:": "MOTTAKER:",
  "CUSTOMER:": "KUNDE:",
  "Order No:": "Ordrenr.:",
  "Ordered Articles:": "Bestilte artikler:",
  "Items Transferred:": "Overførte varer:",
  "Est. Parcel Weight:": "Est. pakkevekt:",
  "Shipment Parcel Weight Info:": "Informasjon om pakkevekt:",
  "Shipment Parcel Weight:": "Pakkevekt:",
  "Total Parcel Weight": "Total pakkevekt",
  "Packaging Weight:": "Emballasjevekt:",
  "Garment Weight:": "Plaggvekt:",
  "Garment Color:": "Plaggfarge:",
  "Carton Garment Color:": "Plaggfarge i kartong:",
  "Total Items in Box:": "Totalt antall varer i boks:",
  "LAST BOX (MIXED SIZES)": "SISTE BOKS (BLANDEDE STØRRELSER)",
  "📦 Mixed Sizes Carton (Solid Color / Assorted Sizes)": "📦 Kartong med blandede størrelser (ensfarget / ulike størrelser)",
  "Solid Color Assorted Sizes Pack": "Ensfarget pakke med ulike størrelser",
  "Solid Color Carton": "Ensfarget kartong",
  "Generate Mixed Carton Sticker for the last leftover box": "Lag klistremerke for blandet kartong til siste restboks",
  "Combined DXF Sheet": "Samlet DXF-ark",
  "Combined Sheet (.dxf)": "Samlet ark (.dxf)",
  "Combined Cartons Sheet (.dxf)": "Samlet kartongark (.dxf)",
  "All Cartons ZIP (.zip)": "Alle kartonger ZIP (.zip)",
  "All Cartons ZIP (1-Click)": "Alle kartonger ZIP (ett klikk)",
  "Mixed Cartons ZIP (.zip)": "Blandede kartonger ZIP (.zip)",
  "Download All Cartons ZIP": "Last ned alle kartonger som ZIP",
  "1-Click Download ALL Mixed Cartons (.dxf & .svg) in a ZIP": "Last ned ALLE blandede kartonger (.dxf og .svg) i én ZIP med ett klikk",
  "1-Click Download ALL Mixed Cartons in a ZIP": "Last ned ALLE blandede kartonger i én ZIP med ett klikk",
  "1-Click download ALL mixed cartons DXF & SVG files inside a ZIP": "Last ned ALLE DXF- og SVG-filer for blandede kartonger i én ZIP med ett klikk",
  "Download all mixed cartons in 1 combined CAD sheet": "Last ned alle blandede kartonger i ett samlet CAD-ark",
  "Download AutoCAD DXF CAD format": "Last ned AutoCAD DXF-format",
  "Download AutoCAD DXF CAD format for this size": "Last ned AutoCAD DXF-format for denne størrelsen",
  "Download Vector SVG format (Double-click opens directly in Chrome/Edge)": "Last ned vektor-SVG (dobbeltklikk åpner direkte i Chrome/Edge)",
  "Download Vector SVG format (Opens directly in Chrome, Edge, Illustrator, Plotters)": "Last ned vektor-SVG (åpnes direkte i Chrome, Edge, Illustrator, plottere)",
  "Download Vector SVG format (Opens in Chrome, Edge, Illustrator, Plotters)": "Last ned vektor-SVG (åpnes i Chrome, Edge, Illustrator, plottere)",
  "Download All Mixed Cartons combined on 1 continuous CAD sheet (.dxf)": "Last ned alle blandede kartonger samlet på ett CAD-ark (.dxf)",
  "Combined Multi-Carton CAD Sheet (.dxf) downloaded!": "Samlet CAD-ark for flere kartonger (.dxf) lastet ned!",
  "Combined multi-carton CAD sheet (.dxf)": "Samlet CAD-ark for flere kartonger (.dxf)",
  "1-Click Mixed Cartons CAD ZIP bundle downloaded!": "ZIP med CAD for blandede kartonger lastet ned!",
  "1-Click Mixed Cartons ZIP bundle downloaded!": "ZIP med blandede kartonger lastet ned!",
  "Generating 1-Click ZIP with all mixed carton CAD (.dxf) & Vector (.svg) files...": "Genererer ZIP med alle CAD- (.dxf) og vektorfiler (.svg) for blandede kartonger...",
  "Packaging all mixed carton CAD (.dxf) & SVG files in ZIP...": "Pakker alle CAD- (.dxf) og SVG-filer for blandede kartonger i ZIP...",
  "Failed to generate CAD DXF file": "Kunne ikke generere CAD DXF-fil",
  "Failed to generate Vector CAD file": "Kunne ikke generere vektor-CAD-fil",
  "Failed to generate Vector SVG file": "Kunne ikke generere vektor-SVG-fil",
  "Failed to generate ZIP archive": "Kunne ikke generere ZIP-arkiv",
  "Failed to generate combined CAD sheet": "Kunne ikke generere samlet CAD-ark",
  "A4 Sheet (2×7 = 14 Labels/Page)": "A4-ark (2×7 = 14 etiketter/side)",
  "A4 Sheet (3×8 = 24 Labels/Page)": "A4-ark (3×8 = 24 etiketter/side)",
  "Thermal Roll (4\" × 2\" / 100×50mm)": "Termisk rull (4\" × 2\" / 100×50 mm)",
  "PNG, JPG, WEBP, SVG": "PNG, JPG, WEBP, SVG",

  // Article form / care label
  "Care Label / Symbols": "Vaskeetikett / symboler",
  "Washing Care Label Photo": "Bilde av vaskeetikett",
  "Washing Instructions": "Vaskeanvisning",
  "Washing Instructions Preview": "Forhåndsvisning av vaskeanvisning",
  "Click to browse or replace care label": "Klikk for å bla eller bytte vaskeetikett",
  "Click to browse or replace photo": "Klikk for å bla eller bytte bilde",
  "Garment Article": "Plaggartikkel",
  "Garment Article Label": "Etikett for plaggartikkel",
  "Garment Hangtag Card": "Hangtag-kort for plagg",
  "Workwear Logo Placement:": "Plassering av arbeidsklærlogo:",
  "Back Reflective Print": "Reflekstrykk på ryggen",
  "Front Left Chest Embroidery": "Brodering foran på venstre bryst",
  "Right Sleeve Badge": "Merke på høyre erme",
  "Create a Nordic Prowear inventory article with dynamic style-number variants.": "Opprett en Nordic Prowear-lagerartikkel med dynamiske stilnummervarianter.",
  "Update article attributes, style-number variants, and inventory metadata.": "Oppdater artikkelegenskaper, stilnummervarianter og lagerdata.",
  "Product & images saved successfully": "Produkt og bilder lagret",
  "Product & images updated successfully": "Produkt og bilder oppdatert",
  "Failed to load product": "Kunne ikke laste produkt",
  "Loading product...": "Laster produkt...",
  "Category created successfully": "Kategori opprettet",
  "Category updated successfully": "Kategori oppdatert",
  "Category description": "Kategoribeskrivelse",
  "Enter category name": "Skriv inn kategorinavn",
  "Create a new category": "Opprett en ny kategori",
  "Failed to load categories": "Kunne ikke laste kategorier",
  "At least one measurement row is required": "Minst én målrad er påkrevd",
  "e.g. Chest Width": "f.eks. Brystbredde",
  "Cotton blend": "Bomullsblanding",

  // CRM: customers, leads, tasks, tickets
  "Customer profile not found": "Kundeprofil ikke funnet",
  "Customer updated successfully": "Kunde oppdatert",
  "Failed to load customer": "Kunne ikke laste kunde",
  "Failed to load customers for dropdown": "Kunne ikke laste kunder til nedtrekksliste",
  "Loading profile...": "Laster profil...",
  "Loading order history...": "Laster ordrehistorikk...",
  "Loading invoice details...": "Laster fakturadetaljer...",
  "Loading B2B customer orders...": "Laster B2B-kundebestillinger...",
  "Auto-generated if empty (e.g. CUST-2026-0001)": "Genereres automatisk hvis tom (f.eks. CUST-2026-0001)",
  "Failed to load leads": "Kunne ikke laste leads",
  "Failed to delete lead": "Kunne ikke slette lead",
  "Failed to update lead stage": "Kunne ikke oppdatere lead-fase",
  "Lead deleted successfully": "Lead slettet",
  "Log Lead Activity": "Logg lead-aktivitet",
  "Send Lead Email": "Send lead-e-post",
  "Write the email body here.": "Skriv e-postteksten her.",
  "Capture meeting notes, call outcomes, next steps, or important context.": "Noter møtenotater, samtaleresultater, neste steg eller viktig kontekst.",
  "Create Task": "Opprett oppgave",
  "Create New Ticket": "Opprett ny sak",
  "Raise a new support request for a customer or general issue.": "Opprett en ny supporthenvendelse for en kunde eller et generelt problem.",
  "Detailed description of the issue...": "Detaljert beskrivelse av problemet...",
  "e.g., Billing, Technical, Shipping": "f.eks. Fakturering, Teknisk, Frakt",
  "e.g., Unable to track order #1234": "f.eks. Kan ikke spore ordre #1234",
  "Support ticket created successfully": "Supportsak opprettet",
  "Ticket updated successfully": "Sak oppdatert",
  "Failed to update ticket": "Kunne ikke oppdatere saken",
  "Failed to load ticket details": "Kunne ikke laste saksdetaljer",
  "Loading ticket details...": "Laster saksdetaljer...",
  "Task created successfully": "Oppgave opprettet",
  "Task updated successfully": "Oppgave oppdatert",
  "Task deleted": "Oppgave slettet",
  "Task assignment updated": "Oppgavetildeling oppdatert",
  "Reminder scheduled": "Påminnelse planlagt",
  "Failed to delete task": "Kunne ikke slette oppgave",
  "Failed to load task": "Kunne ikke laste oppgave",
  "Failed to load task references": "Kunne ikke laste oppgavereferanser",
  "Add delivery notes, dependencies, and customer context.": "Legg til leveringsnotater, avhengigheter og kundekontekst.",
  "Adjust due dates, ownership, customer links, and execution status from one task workspace.": "Juster frister, eierskap, kundekoblinger og status fra ett oppgaveområde.",
  "Review due dates, CRM links, assignment changes, reminders, and activity history.": "Se over frister, CRM-koblinger, endringer i tildeling, påminnelser og aktivitetshistorikk.",
  "Open a new customer or lead follow-up with ownership, due date, and reminder-ready metadata.": "Opprett en ny kunde- eller lead-oppfølging med eier, frist og påminnelsesdata.",
  "Why is this task being reassigned?": "Hvorfor blir denne oppgaven omfordelt?",
  "Customer follow-up after sample dispatch": "Kundeoppfølging etter sending av prøver",
  "Call customer after sample approval.": "Ring kunden etter godkjenning av prøven.",
  "Prepare bulk order quotation": "Utarbeid tilbud på storbestilling",
  "Filter Status:": "Filtrer status:",
  "Priority": "Prioritet",

  // Lead priority labels
  "A+ (Høyest potensial / Highest Potential)": "A+ (Høyest potensial)",
  "A (Høyt potensial / High Potential)": "A (Høyt potensial)",
  "A- (Middels-høyt / Medium-High)": "A- (Middels-høyt)",
  "B+ (Middels potensial / Medium Potential)": "B+ (Middels potensial)",
  "B (Mindre / Standard)": "B (Mindre / standard)",
  "Prioritet: A+": "Prioritet: A+",
  "Prioritet: A": "Prioritet: A",
  "Prioritet: A-": "Prioritet: A-",
  "Prioritet: B+": "Prioritet: B+",
  "Prioritet: B": "Prioritet: B",
  "Tender (Offentlig / Anbud)": "Anbud (offentlig)",

  // CRM reports / analytics
  "Revenue Intelligence": "Inntektsinnsikt",
  "Pipeline & Lead Intelligence": "Pipeline og lead-innsikt",
  "Customer Lifecycle Insights": "Innsikt i kundelivssyklus",
  "Lead Conversion Funnel": "Lead-konverteringstrakt",
  "Leads by Source": "Leads etter kilde",
  "Leads by Status": "Leads etter status",
  "Monthly Lead Creation Trend": "Månedlig utvikling i nye leads",
  "Monthly Customer Growth": "Månedlig kundevekst",
  "Customers by Type": "Kunder etter type",
  "Revenue by Customer Type": "Inntekt etter kundetype",
  "Revenue by Month": "Inntekt per måned",
  "Revenue from Customers": "Inntekt fra kunder",
  "Revenue Gap": "Inntektsgap",
  "Revenue Realization": "Inntektsrealisering",
  "Top Customers by Revenue": "Toppkunder etter inntekt",
  "Top Customer Revenue": "Inntekt fra toppkunde",
  "Closed Revenue": "Lukket inntekt",
  "Expected Revenue": "Forventet inntekt",
  "Total Leads": "Totalt antall leads",
  "Won Leads": "Vunnede leads",
  "Lost Leads": "Tapte leads",
  "Win Share": "Vinnandel",
  "All tracked leads": "Alle sporede leads",
  "Converted opportunities": "Konverterte muligheter",
  "Opportunities dropped": "Mistede muligheter",
  "Open pipeline potential": "Åpent pipeline-potensial",
  "Remaining opportunity in pipeline": "Gjenstående mulighet i pipeline",
  "Current stage distribution": "Fordeling per fase",
  "Stage-by-stage opportunity progression": "Fremdrift for muligheter fase for fase",
  "Acquisition channels driving pipeline": "Kanaler som driver pipeline",
  "Active customer categories in data": "Aktive kundekategorier i dataene",
  "Customers marked active": "Kunder merket som aktive",
  "Customer segmentation overview": "Oversikt over kundesegmentering",
  "Contribution split by customer segment": "Bidrag fordelt på kundesegment",
  "Closed revenue relative to expected pipeline": "Lukket inntekt i forhold til forventet pipeline",
  "Closed revenue tied to customer records": "Lukket inntekt knyttet til kunder",
  "Closed revenue trend over time": "Utvikling i lukket inntekt over tid",
  "Highest contributor in selected period": "Største bidragsyter i valgt periode",
  "Highest-value customer accounts in the selected period": "Mest verdifulle kundekontoer i valgt periode",
  "Won leads as percentage of total": "Vunnede leads som prosent av totalt",
  "New customers added month over month": "Nye kunder måned for måned",
  "New opportunities created by month": "Nye muligheter per måned",
  "Bar view for quick executive comparison": "Stolpevisning for rask sammenligning",
  "Measure lead conversion velocity, acquisition channel efficiency, and pipeline progression dynamics.": "Mål konverteringshastighet for leads, effektivitet i kanaler og utvikling i pipeline.",
  "Analyze customer segment concentration, acquisition trends, and revenue contribution profiles.": "Analyser konsentrasjon i kundesegmenter, anskaffelsestrender og inntektsbidrag.",
  "Analyze revenue trajectories, realization rates, and commercial performance across customer segments.": "Analyser inntektsutvikling, realiseringsgrad og kommersiell ytelse på tvers av kundesegmenter.",

  // B2B portal / Visma PunchOut
  "B2B Customer Portal Login": "Innlogging for B2B-kundeportal",
  "Contracted Assortment & Agreed Pricing Only": "Kun avtalt sortiment og avtalte priser",
  "Authenticating Visma eHandel PunchOut Session...": "Autentiserer Visma eHandel PunchOut-økt...",
  "Verifying contracted prices & municipality access permissions": "Verifiserer avtalte priser og kommunens tilgangsrettigheter",
  "Current PunchOut Cart": "Gjeldende PunchOut-handlekurv",
  "PunchOut Cart Transferred to Visma": "PunchOut-handlekurv overført til Visma",
  "PunchOut Cart successfully transferred to Visma eHandel!": "PunchOut-handlekurven er overført til Visma eHandel!",
  "PunchOut Session Expired or Invalid": "PunchOut-økten er utløpt eller ugyldig",
  "PunchOut Session ID is missing": "PunchOut-økt-ID mangler",
  "Please launch Nordic Prowear again from your Visma eHandel procurement portal.": "Start Nordic Prowear på nytt fra innkjøpsportalen din i Visma eHandel.",
  "Simulate Visma Approval & View Orders": "Simuler Visma-godkjenning og vis bestillinger",
  "Target Hook URL:": "Mål-hook-URL:",
  "Your cart is empty! Select products before returning to Visma eHandel.": "Handlekurven din er tom! Velg produkter før du går tilbake til Visma eHandel.",

  // Misc
  "Oslo, Norway • B2B Division": "Oslo, Norge • B2B-avdelingen",
  "Oslo, Norway • B2B Sales Division": "Oslo, Norge • B2B-salgsavdelingen",
  "Oslo, Norway • POS Counter": "Oslo, Norge • POS-disk",
  "Nordic Prowear Logo": "Nordic Prowear-logo",
  "Logo": "Logo",
  "Pending Stock Out Fulfillment": "Venter på utlevering (Stock Out)",
  "Low Stock Products": "Produkter med lavt lager",
  "Reorder Recommended": "Etterbestilling anbefalt",
  "Recent Transactions": "Siste transaksjoner",
  "Low Stock Alerts": "Varsler om lavt lager",
  "No records found": "Ingen poster funnet",
  "left": "igjen",
  "Healthy Articles": "Artikler med god beholdning",
  "Out Of Stock": "Utsolgt",
  "Nordic Prowear Operational Overview": "Operativ oversikt for Nordic Prowear",
  "Nordic Prowear ERP": "Nordic Prowear ERP",
};

export default extraPhrasesNo;
