// Additional English -> Norwegian (bokmål) phrases for UI text that is not wired to t().
// Used by the DOM auto-translator when Norwegian is selected (see LanguageContext.jsx).
const phrases = {
  // Barcode page / print modal
  "\"Download Excel (+ Barcodes)\"": "«Last ned Excel (+ strekkoder)»",
  "\"Mixed Carton Sticker\"": "«Etikett for blandet kartong»",
  "\"Print All Sizes\"": "«Skriv ut alle størrelser»",
  "Thermal Roll (4\" × 2\" / 100×50mm)": "Termisk rull (4\" × 2\" / 100×50 mm)",
  "Thermal Roll (4″ × 2″ / 100×50mm)": "Termisk rull (4″ × 2″ / 100×50 mm)",
  "Chest Width": "Brystbredde",
  "Width down": "Bredde nede",
  "Sleeve Width": "Ermebredde",
  "Width neckopening": "Bredde halsåpning",
  "Height neck opening at the back": "Høyde halsåpning bak",
  "Height v-neck-opening at the front": "Høyde v-halsåpning foran",
  "Back length from neck opening": "Rygglengde fra halsåpning",
  "Sleeve length from neck opening": "Ermelengde fra halsåpning",
  "Distance chest pocket from side seam": "Avstand brystlomme fra sidesøm",
  "medium blue": "mellomblå",  "Download Excel (+ Barcodes)": "Last ned Excel (+ strekkoder)",
  "Mixed Carton Sticker": "Etikett for blandet kartong",
  "Print All Sizes": "Skriv ut alle størrelser",
  "Print All Sizes (": "Skriv ut alle størrelser (",
  "Click": "Klikk",
  "for standard garment labels,": "for standard plaggetiketter,",
  "for the last leftover box sticker with master barcode & breakdown, or": "for etiketten på siste restekartong med hovedstrekkode og oppdeling, eller",
  "Back to Articles": "Tilbake til artikler",
  "All Sizes for Article #": "Alle størrelser for artikkel #",
  "Variants)": "Varianter)",
  "Color:": "Farge:",
  "Size:": "Størrelse:",
  "Excel Export": "Excel-eksport",
  "Print Sticker": "Skriv ut etikett",
  "Save CAD (.dxf)": "Lagre CAD (.dxf)",
  "Save PNG": "Lagre PNG",
  "Save Vector (.svg)": "Lagre vektor (.svg)",
  "Generating article barcode label...": "Genererer strekkodeetikett for artikkel...",
  "Generating barcode...": "Genererer strekkode...",
  "Excel": "Excel",
  "Excel (.xlsx)": "Excel (.xlsx)",
  "Export CAD (.dxf)": "Eksporter CAD (.dxf)",
  "Exporting...": "Eksporterer...",
  "Print Labels Now": "Skriv ut etiketter nå",
  "Carton Sticker": "Kartongetikett",
  "(Solid": "(Ensfarget",
  "(Solid Color)": "(Ensfarget)",
  "• Mixed sizes)": "• Blandede størrelser)",
  "⚠️ LAST BOX (MIXED SIZES)": "⚠️ SISTE ESKE (BLANDEDE STØRRELSER)",
  "🏷️ Individual Garment Labels (": "🏷️ Individuelle plaggetiketter (",
  "📦 MASTER CARTON BARCODE -": "📦 HOVEDKARTONG-STREKKODE -",
  "1 Label per Stock Unit (": "1 etikett per lagerenhet (",
  "1 Label per Variant (": "1 etikett per variant (",
  "labels)": "etiketter)",
  "ASSORTED SIZES": "BLANDEDE STØRRELSER",
  "Brand Badge": "Merkebadge",
  "Carton Description:": "Kartongbeskrivelse:",
  "color(s)": "farge(r)",
  "Color(s) •": "Farge(r) •",
  "e.g. NP10002": "f.eks. NP10002",
  "e.g. Z15 (Assorted Sizes)": "f.eks. Z15 (blandede størrelser)",
  "Fill Stock (": "Fyll lager (",
  "Garment Logistics & Warehousing": "Plaggelogistikk og lagerhold",
  "Order No / Ref:": "Ordrenr. / ref.:",
  "pcs /": "stk /",
  "Show Price (NOK)": "Vis pris (NOK)",
  "Size / Color": "Størrelse / farge",
  "Size Breakdown (": "Størrelsesfordeling (",
  "sizes)": "størrelser)",
  "Sizes)": "Størrelser)",
  "SKU:": "SKU:",
  "Solid Color Assorted Sizes Carton •": "Ensfarget kartong med blandede størrelser •",
  "Stock:": "Lager:",
  "Style Article:": "Stilartikkel:",
  "Thermal Roll (4\" × 2\" / 100×50mm)": "Termisk rull (4\" × 2\" / 100×50 mm)",
  "Total Sizes/Variants": "Totalt størrelser/varianter",
  "vars)": "var.)",
  "No sizes selected for": "Ingen størrelser valgt for",

  // Excel export headers
  "Article Name": "Artikkelnavn",
  "Barcode No": "Strekkodenr.",
  "Barcode Sticker (Image)": "Strekkodeetikett (bilde)",
  "Price (NOK)": "Pris (NOK)",
  "Stock Qty": "Lagerantall",
  "Stock Status": "Lagerstatus",
  "Style No / Code": "Stilnr. / kode",

  // Tasks
  "Activity History": "Aktivitetshistorikk",
  "Assignment History": "Tildelingshistorikk",
  "Assignment Note": "Tildelingsnotat",
  "CRM Links": "CRM-koblinger",
  "Custom Contact": "Egendefinert kontakt",
  "Delivery Channel": "Leveringskanal",
  "Email + SMS": "E-post + SMS",
  "Lead": "Lead",
  "Reassign Task": "Tildel oppgave på nytt",
  "Recipient Email": "Mottakers e-post",
  "Recipient Phone": "Mottakers telefon",
  "Recipient:": "Mottaker:",
  "Reminder Date": "Påminnelsesdato",
  "Reminder History": "Påminnelseshistorikk",
  "Reminder Note": "Påminnelsesnotat",
  "Reminder Time": "Påminnelsestidspunkt",
  "Reminders": "Påminnelser",
  "Schedule Reminder": "Planlegg påminnelse",
  "Send To": "Send til",
  "Sent": "Sendt",
  "Add Reminder": "Legg til påminnelse",
  "Scheduling...": "Planlegger...",
  "Update Assignment": "Oppdater tildeling",
  "Updating...": "Oppdaterer...",
  "No active assignee": "Ingen aktiv ansvarlig",
  "No assignment note": "Ingen tildelingsnotat",
  "No reminder note": "Ingen påminnelsesnotat",
  "No assignment changes recorded.": "Ingen tildelingsendringer registrert.",
  "No reminders created yet.": "Ingen påminnelser opprettet ennå.",
  "Assigned User": "Tildelt bruker",
  "Related Customer": "Relatert kunde",
  "Related Lead": "Relatert lead",
  "No customer linked": "Ingen kunde koblet",
  "No lead linked": "Ingen lead koblet",
  "Unassigned": "Ikke tildelt",
  "Task Information": "Oppgaveinformasjon",
  "Define the work item, due date, priority, and CRM linkage in one place.": "Definer oppgaven, forfallsdato, prioritet og CRM-kobling på ett sted.",
  "Calendar view of task due dates.": "Kalendervisning av oppgavenes forfallsdatoer.",
  "No tasks": "Ingen oppgaver",
  "No tasks due on this day.": "Ingen oppgaver forfaller denne dagen.",
  "No tasks found.": "Ingen oppgaver funnet.",
  "Loading task form...": "Laster oppgaveskjema...",
  "Loading task...": "Laster oppgave...",
  "Related Tasks": "Relaterte oppgaver",
  "No tasks linked to this lead.": "Ingen oppgaver koblet til denne leaden.",
  "Assigned user:": "Tildelt bruker:",
  "Lead:": "Lead:",

  // Leads / customers / CRM
  "Activity Type": "Aktivitetstype",
  "Start": "Start",
  "End": "Slutt",
  "Save Activity": "Lagre aktivitet",
  "By": "Av",
  "Due": "Forfall",
  "Unified Activity Timeline": "Samlet aktivitetstidslinje",
  "No activity recorded yet.": "Ingen aktivitet registrert ennå.",
  "No details added": "Ingen detaljer lagt til",
  "No notes available": "Ingen notater tilgjengelig",
  "Opportunity Snapshot": "Salgsmulighet – oversikt",
  "Norge": "Norge",
  "Contact Details": "Kontaktdetaljer",
  "Business Context": "Forretningskontekst",
  "Update Customer": "Oppdater kunde",
  "Loading customer...": "Laster kunde...",
  "Loading customer directory...": "Laster kundekatalog...",
  "Update contact details, status, and account information without leaving the CRM workspace.": "Oppdater kontaktdetaljer, status og kontoinformasjon uten å forlate CRM-arbeidsområdet.",
  "& Profile": "& profil",
  "MVA:": "MVA:",
  "• (MVA:": "• (MVA:",
  "Email Conversations": "E-postsamtaler",
  "No email conversations yet.": "Ingen e-postsamtaler ennå.",
  "Last message": "Siste melding",
  "From": "Fra",
  "To": "Til",
  "Message": "Melding",
  "Sending...": "Sender...",
  "Loading customer analytics...": "Laster kundeanalyse...",
  "Loading lead analytics...": "Laster leadanalyse...",
  "Loading revenue analytics...": "Laster inntektsanalyse...",
  "Revenue": "Inntekt",
  "Search customer, company, type, orders, revenue...": "Søk etter kunde, firma, type, ordrer, inntekt...",

  // Reports
  "Inventory Valuation": "Lagerverdi",
  "Stock In Log": "Varemottakslogg",
  "Stock Out Log (Shipments)": "Vareutgangslogg (forsendelser)",
  "Product Movement": "Produktbevegelse",
  "Low Stock Alert": "Varsel om lav beholdning",
  "Customer Orders": "Kundeordrer",
  "Customer Purchases": "Kundekjøp",
  "Open Orders Pipeline": "Åpne ordrer – pipeline",
  "All Sources": "Alle kilder",
  "All Types": "Alle typer",
  "Wholesale": "Engros",
  "Facebook": "Facebook",
  "Instagram": "Instagram",
  "WhatsApp": "WhatsApp",
  "Referral": "Henvisning",
  "Walk In": "Direkte besøk",
  "Trade Show": "Messe",
  "Existing Customer": "Eksisterende kunde",
  "Other": "Annet",
  "Healthy": "Frisk",

  // Sales / POS / orders
  "Select Customer": "Velg kunde",
  "Barcode Camera Scanner": "Strekkodeskanner (kamera)",
  "• Stock:": "• Lager:",
  "• Phone:": "• Telefon:",
  "No items in cart yet. Select a product or scan a barcode above.": "Ingen varer i handlekurven ennå. Velg et produkt eller skann en strekkode ovenfor.",
  "Order Summary": "Ordresammendrag",
  "Reset 25% VAT": "Tilbakestill 25 % MVA",
  "Complete Sale & Print Receipt": "Fullfør salg og skriv ut kvittering",
  "- NOK": "- NOK",
  "+ NOK": "+ NOK",
  "= NOK": "= NOK",
  "JazzCash": "JazzCash",
  "EasyPaisa": "EasyPaisa",
  "Items and quantities cannot be edited directly to preserve inventory audit trails. To change items, please delete this sale and create a new one.": "Varer og antall kan ikke redigeres direkte for å bevare revisjonssporet for lageret. Slett dette salget og opprett et nytt for å endre varer.",
  "Products (": "Produkter (",
  "Search invoice, customer, product, payment, total, date...": "Søk etter faktura, kunde, produkt, betaling, sum, dato...",
  "Syncing invoice sales records...": "Synkroniserer fakturaer og salgsposter...",
  "Search by product, SKU, quantity, condition, reason, user, or date...": "Søk etter produkt, SKU, antall, tilstand, årsak, bruker eller dato...",
  "Loading returns...": "Laster returer...",
  "No return records found.": "Ingen returposter funnet.",
  "Submit Return": "Send inn retur",
  "Saving Changes...": "Lagrer endringer...",
  "Note: Changing status to/from \"Usable\" will automatically adjust current stock.": "Merk: Å endre status til/fra «Brukbar» justerer lagerbeholdningen automatisk.",
  "This item was marked as non-usable. No stock adjustments were made to the available inventory.": "Denne varen ble markert som ikke brukbar. Ingen lagerjusteringer ble gjort.",
  "This item was marked as USABLE. The stock level of the product was automatically increased upon processing.": "Denne varen ble markert som BRUKBAR. Lagerbeholdningen for produktet ble automatisk økt ved behandling.",
  "No specific reason provided for this return.": "Ingen spesifikk årsak oppgitt for denne returen.",
  "Date:": "Dato:",
  "Nordic Prowear AS": "Nordic Prowear AS",
  "Client": "Kunde",
  "Fulfilling Stock Out...": "Gjennomfører vareutgang...",
  "No B2B customer orders found.": "Ingen B2B-kundeordrer funnet.",
  "Total B2B Orders:": "Totalt antall B2B-ordrer:",
  "Contact:": "Kontakt:",
  "Fulfilled •": "Gjennomført •",
  "DN:": "LS:",

  // Portal / punchout
  "B2B Portal": "B2B-portal",
  "B2B Catalog": "B2B-katalog",
  "B2B Client": "B2B-kunde",
  "B2B-CLIENT": "B2B-KUNDE",
  "Catalogue": "Katalog",
  "My Orders": "Mine ordrer",
  "Order History": "Ordrehistorikk",
  "Shopping Cart": "Handlekurv",
  "Order Notes": "Ordrenotater",
  "Placing Order...": "Legger inn ordre...",
  "CUSTOMER & DELIVERY:": "KUNDE OG LEVERING:",
  "Delivery:": "Levering:",
  "Registered Address": "Registrert adresse",
  "Garment:": "Plagg:",
  "Garment Weight": "Plaggvekt",
  "Packaging Box": "Emballasjeeske",
  "Est. Total Parcel": "Est. total pakkevekt",
  "kg + Box:": "kg + eske:",
  "Some items lack weight specifications.": "Noen varer mangler vektspesifikasjoner.",
  "Done": "Ferdig",
  "Auto Profile": "Automatisk profil",
  "Staff Mode": "Ansattmodus",
  "Nordic Partner": "Nordic-partner",
  "B2B Order Confirmation PDF": "B2B-ordrebekreftelse (PDF)",
  "VAT (25% MVA):": "MVA (25 %):",
  "VAT (25%):": "MVA (25 %):",
  "Apparel": "Klær",
  "Nordic Prowear B2B Customer Portal. All rights reserved.": "Nordic Prowear B2B-kundeportal. Alle rettigheter forbeholdt.",
  "Fredrikstad Municipality Authorized Catalogue": "Autorisert katalog for Fredrikstad kommune",
  "Visma PunchOut Active": "Visma PunchOut aktiv",
  "Connected Buyer:": "Tilkoblet kjøper:",
  "articles ready": "artikler klare",
  "Uncontracted products are strictly filtered out per agreement. Select your required clothing sizes, colors, and workwear branding options.": "Produkter utenfor avtalen er strengt filtrert bort. Velg ønskede klesstørrelser, farger og merkealternativer for arbeidstøy.",
  "Article Photo": "Artikkelbilde",
  "Washing Care": "Vaskeråd",
  "Workwear": "Arbeidstøy",
  "Workwear & Safety": "Arbeidstøy og sikkerhet",
  "Work Trousers": "Arbeidsbukser",
  "Safety Equipment": "Verneutstyr",
  "Front Left Chest Logo": "Logo foran, venstre bryst",
  "Transfer Cart to Visma (": "Overfør handlekurv til Visma (",
  "items)": "varer)",
  "Go to B2B Login Portal": "Gå til B2B-innloggingsportal",
  "✕ Close": "✕ Lukk",
  "Close & Continue Shopping": "Lukk og fortsett å handle",
  "Copy XML": "Kopier XML",
  "Protocol:": "Protokoll:",
  "(UNSPSC Workwear Code 46181500)": "(UNSPSC-kode for arbeidstøy 46181500)",
  "Do Not Bleach.": "Må ikke blekes.",

  // Products / forms
  "Variant Style No": "Variantens stilnr.",
  "Display Name": "Visningsnavn",
  "Colour": "Farge",
  "No size / one size": "Ingen størrelse / én størrelse",
  "Purchase / Cost Price (NOK)": "Innkjøps- / kostpris (NOK)",
  "Sale Price (NOK)": "Salgspris (NOK)",
  "USD Invoice Helper": "USD-fakturahjelper",
  "Hide USD Helper": "Skjul USD-hjelper",
  "Apply NOK Price": "Bruk NOK-pris",
  "Supplier / External Barcode": "Leverandør- / ekstern strekkode",
  "Choose Article Photo": "Velg artikkelbilde",
  "Choose Care Label Photo": "Velg bilde av vaskelapp",
  "Washing Care Text & Instructions": "Vaskerådtekst og instruksjoner",
  "Description / Notes": "Beskrivelse / notater",
  "Save Article": "Lagre artikkel",
  "Do Not Bleach. Tumble Dry Low.": "Må ikke blekes. Tørketrommel på lav varme.",
  "65% Polyester, 35% Cotton": "65 % polyester, 35 % bomull",
  "e.g. Invoice NP10002 (+20% CFR Oslo)": "f.eks. Faktura NP10002 (+20 % CFR Oslo)",
  "White": "Hvit",
  "Loading apparel article details & garment photos...": "Laster artikkeldetaljer og plaggbilder...",
  "IMG-Pending": "IMG-venter",
  "NOK 0": "NOK 0",
  "System Admin": "Systemadministrator",
  "Exit Fullscreen": "Avslutt fullskjerm",
  "View Fullscreen": "Vis i fullskjerm",
  "Create User": "Opprett bruker",
  "New Password (leave blank to keep current)": "Nytt passord (la stå tomt for å beholde nåværende)",
  "e.g. John Doe": "f.eks. Ola Nordmann",
  "Syncing console users...": "Synkroniserer brukere...",
  "Are you sure you want to delete this user? This will permanently remove their access.": "Er du sikker på at du vil slette denne brukeren? Dette fjerner tilgangen deres permanent.",
  "Close sidebar": "Lukk sidepanel",
  "Open sidebar": "Åpne sidepanel",
  "Verifying secure session...": "Verifiserer sikker økt...",
  "Securing your session...": "Sikrer økten din...",

  // Support tickets
  "Cancel Editing": "Avbryt redigering",
  "Update Ticket": "Oppdater sak",
  "Save Ticket": "Lagre sak",
  "General": "Generelt",
  "General Support": "Generell støtte",
  "System": "System",
  "No description provided.": "Ingen beskrivelse oppgitt.",
  "Opened on": "Åpnet",
  "Ticket": "Sak",

  // Category form
  "Save Category": "Lagre kategori",
  "Saving...": "Lagrer...",

  // Server messages shown in toasts
  "`from` date must be earlier than or equal to `to` date": "Fra-datoen må være tidligere enn eller lik til-datoen",
  "Access denied": "Ingen tilgang",
  "B2B Customer Order not found": "B2B-kundeordre ikke funnet",
  "Barcode generation failed": "Generering av strekkode mislyktes",
  "Barcode not found": "Strekkode ikke funnet",
  "Base style number and purchase price are required": "Hovedstilnummer og innkjøpspris er påkrevd",
  "Brevo configuration is missing": "Brevo-konfigurasjon mangler",
  "Category already exists": "Kategorien finnes allerede",
  "Category not found": "Kategori ikke funnet",
  "Could not retrieve verified email from Google.": "Kunne ikke hente verifisert e-post fra Google.",
  "Current password is required to set a new password": "Nåværende passord kreves for å sette nytt passord",
  "Custom email recipient is required for combined reminders": "Egendefinert e-postmottaker kreves for kombinerte påminnelser",
  "Custom email recipient is required for email reminders": "Egendefinert e-postmottaker kreves for e-postpåminnelser",
  "Custom phone recipient is required for combined reminders": "Egendefinert telefonmottaker kreves for kombinerte påminnelser",
  "Custom phone recipient is required for SMS reminders": "Egendefinert telefonmottaker kreves for SMS-påminnelser",
  "Customer already exists": "Kunden finnes allerede",
  "Customer not found": "Kunde ikke funnet",
  "Customer profile not found for PunchOut session": "Kundeprofil ikke funnet for PunchOut-økt",
  "Customer record could not be resolved. Please log in again.": "Kundeposten kunne ikke identifiseres. Vennligst logg inn på nytt.",
  "Customer with this email or phone number already exists.": "En kunde med denne e-postadressen eller dette telefonnummeret finnes allerede.",
  "Delivery Note not found": "Pakkeseddel ikke funnet",
  "Email already in use": "E-postadressen er allerede i bruk",
  "Email body content is required": "E-postinnhold kreves",
  "Email conversation not found": "E-postsamtale ikke funnet",
  "Email subject is required": "E-postemne kreves",
  "Failed to generate barcode image": "Kunne ikke generere strekkodebilde",
  "Full name, email, and password are required.": "Fullt navn, e-post og passord er påkrevd.",
  "Garment Stock Management API Running Successfully": "API for plagglagerstyring kjører",
  "Google email is not verified by Google.": "Google-e-posten er ikke verifisert av Google.",
  "Google token does not contain a valid email.": "Google-tokenet inneholder ikke en gyldig e-postadresse.",
  "Invalid credentials": "Ugyldig påloggingsinformasjon",
  "Invalid current password": "Ugyldig nåværende passord",
  "Invalid Google access token.": "Ugyldig Google-tilgangstoken.",
  "Invalid Google authentication token.": "Ugyldig Google-autentiseringstoken.",
  "Invalid login credentials.": "Ugyldig påloggingsinformasjon.",
  "Invalid or expired token": "Ugyldig eller utløpt token",
  "Invalid product items in cart.": "Ugyldige produktlinjer i handlekurven.",
  "Invalid PunchOut Session": "Ugyldig PunchOut-økt",
  "Invalid reminder recipient type": "Ugyldig mottakertype for påminnelse",
  "Lead not found": "Lead ikke funnet",
  "Mandatory Customer Selection: Stock Out requires selecting a customer.": "Kunde må velges: Vareutgang krever at en kunde velges.",
  "No active user found to perform sale transaction": "Ingen aktiv bruker funnet for å utføre salgstransaksjonen",
  "No active user found to perform stock reversion": "Ingen aktiv bruker funnet for å reversere lagerbeholdningen",
  "No matching variants found": "Ingen matchende varianter funnet",
  "Order is already fulfilled/completed": "Ordren er allerede gjennomført/fullført",
  "Order must contain at least one item.": "Ordren må inneholde minst én vare.",
  "Order not found": "Ordre ikke funnet",
  "Please specify item barcode/SKU and quantity for stock out.": "Oppgi varens strekkode/SKU og antall for vareutgang.",
  "Portal access disabled for this account.": "Portaltilgang er deaktivert for denne kontoen.",
  "Product not found": "Produkt ikke funnet",
  "Provide a display name, style name, or item name": "Oppgi et visningsnavn, stilnavn eller varenavn",
  "Recipient email address is required": "Mottakers e-postadresse kreves",
  "Reminder scheduled": "Påminnelse planlagt",
  "Return record not found": "Returpost ikke funnet",
  "Sale not found": "Salg ikke funnet",
  "Selected customer does not exist.": "Valgt kunde finnes ikke.",
  "Selected reminder recipient does not have a phone number": "Valgt påminnelsesmottaker har ikke telefonnummer",
  "Selected reminder recipient does not have an email address": "Valgt påminnelsesmottaker har ikke e-postadresse",
  "Selected reminder recipient must have an email address or phone number": "Valgt påminnelsesmottaker må ha e-postadresse eller telefonnummer",
  "styleNumber, sizes, and measurements are required.": "Stilnummer, størrelser og mål er påkrevd.",
  "Task completed": "Oppgave fullført",
  "Task created": "Oppgave opprettet",
  "Task not found": "Oppgave ikke funnet",
  "Task updated": "Oppgave oppdatert",
  "This article is linked to sales and cannot be deleted": "Denne artikkelen er knyttet til salg og kan ikke slettes",
  "Twilio SMS configuration is missing": "Twilio SMS-konfigurasjon mangler",
  "Unauthorized access": "Uautorisert tilgang",
  "User account is disabled.": "Brukerkontoen er deaktivert.",
  "User account not found": "Brukerkonto ikke funnet",
  "User already exists": "Brukeren finnes allerede",
  "User not found": "Bruker ikke funnet",
  "User or customer profile not found.": "Bruker- eller kundeprofil ikke funnet.",
  "Verified Google email is required.": "Verifisert Google-e-post kreves.",

  // Client toasts (English-only ones)
  "Activity logged": "Aktivitet loggført",
  "Failed to log activity": "Kunne ikke loggføre aktivitet",
  "Email sent successfully": "E-post sendt",
  "Failed to send email": "Kunne ikke sende e-post",
  "Delete failed": "Sletting mislyktes",
  "Update failed": "Oppdatering mislyktes",
  "Export failed": "Eksport mislyktes",
  "Failed to generate PDF": "Kunne ikke lage PDF",
  "Failed to load lead": "Kunne ikke laste lead",
  "No articles to export.": "Ingen artikler å eksportere.",
  "No leads found with selected filters": "Ingen leads funnet med valgte filtre",
  "No report data to export": "Ingen rapportdata å eksportere",
  "Added": "Lagt til",
  "Mixed Carton Sticker downloaded!": "Etikett for blandet kartong lastet ned!",
  "Delivery Note PDF downloaded!": "Pakkeseddel (PDF) lastet ned!",
  // Sales report
  "All customers": "Alle kunder",
  "Walk-in Customer": "Gjestekunde",
  "From date": "Fra dato",
  "To date": "Til dato",
  "Clear filters": "Fjern filtre",
  "sales": "salg",
  "Total:": "Totalt:",
  "Export to Excel (.xlsx)": "Eksporter til Excel (.xlsx)",
  "Download PDF (.pdf)": "Last ned PDF (.pdf)",
  // Sales report (Reports page)
  "Sales Report": "Salgsrapport",
  "invoice Number": "Fakturanummer",
  "customer Name": "Kundenavn",
  "company Name": "Firmanavn",
  "products": "Produkter",
  "total Items": "Antall varer",
  "payment Method": "Betalingsmåte",
  "subtotal": "Delsum",
  "discount": "Rabatt",
  "vat": "MVA",
  "grand Total": "Totalt",
  "date": "Dato",
  "total Sales": "Antall salg",
  "total Items Sold": "Solgte varer",
  "total Vat": "Total MVA",
  "total Revenue": "Total omsetning",
  // Login page
  "Nordic Prowear AS · GDPR Compliant": "Nordic Prowear AS · GDPR-kompatibel",
  "To enable automatic Google One-Tap OAuth popup, set": "For å aktivere automatisk Google One-Tap OAuth-popup, sett",
  "in your": "i din",
  "file.": "-fil.",
  "Enter your real Gmail account to connect and log in to the B2B portal.": "Skriv inn din Gmail-konto for å koble til og logge inn på B2B-portalen.",
  "Sign in with Google": "Logg inn med Google",
  "Your Gmail / Google Email Address": "Din Gmail- / Google-e-postadresse",
  "Your Full Name / Business Name (Optional)": "Ditt fulle navn / firmanavn (valgfritt)",
  "Continue with this Google Account": "Fortsett med denne Google-kontoen",
  "Authenticating...": "Autentiserer...",
  "Continue with Google": "Fortsett med Google",
  "Staff Login": "Ansattinnlogging",
  "B2B Login": "B2B-innlogging",
  "Sign Up": "Registrer deg",
  "Email or Phone": "E-post eller telefon",
  "Email Address": "E-postadresse",
  "Password": "Passord",
  "Forgot?": "Glemt?",
  "Sign In": "Logg inn",
  "Signing in...": "Logger inn...",
  "Company Name": "Firmanavn",
  "Contact Person Name": "Kontaktpersonens navn",
  "Email": "E-post",
  "Phone": "Telefon",
  "Create Account & Browse Catalog": "Opprett konto og bla i katalogen",
  "Creating Account...": "Oppretter konto...",
  "Secure encrypted access portal": "Sikker, kryptert tilgangsportal",
  "Nordic": "Nordic",
  "Prowear": "Prowear",
};

// Sentences that contain variable parts. {0}, {1}... capture the dynamic text.
export const patterns = [
  [
    "Are you sure you want to delete invoice {0}? This will automatically restore stock levels for all items in this sale.",
    "Er du sikker på at du vil slette faktura {0}? Dette gjenoppretter automatisk lagerbeholdningen for alle varer i dette salget.",
  ],
  [
    "Are you sure you want to delete this return record for {0}? This will also reverse the stock adjustment if the item was marked as Usable.",
    "Er du sikker på at du vil slette denne returposten for {0}? Dette reverserer også lagerjusteringen hvis varen ble markert som brukbar.",
  ],
  [
    "Are you sure you want to delete {0}? This action cannot be undone.",
    "Er du sikker på at du vil slette {0}? Denne handlingen kan ikke angres.",
  ],
  ["Assigned user: {0}", "Tildelt bruker: {0}"],
  ["Lead: {0}", "Lead: {0}"],
  ["Size: {0}", "Størrelse: {0}"],
  ["Color: {0}", "Farge: {0}"],
  ["Stock: {0}", "Lager: {0}"],
  ["SKU: {0}", "SKU: {0}"],
  ["Date: {0}", "Dato: {0}"],
  ["Contact: {0}", "Kontakt: {0}"],
  ["Delivery: {0}", "Levering: {0}"],
  ["Garment: {0}", "Plagg: {0}"],
  ["Recipient: {0}", "Mottaker: {0}"],
  ["Opened on {0}", "Åpnet {0}"],
  ["Loading {0}...", "Laster {0}..."],
  ["Article Barcode - {0}", "Artikkelstrekkode - {0}"],
  ["Print Barcode Labels - Article # {0}", "Skriv ut strekkodeetiketter - artikkel # {0}"],
  ["Mixed Carton Barcode Sticker (Last Box) - Article # {0}", "Strekkodeetikett for blandet kartong (siste eske) - artikkel # {0}"],
];

export default phrases;
