import React, { createContext, useContext, useState, useEffect, useMemo } from "react";

const translations = {
  en: {
    // Brand & App Header
    brandTitle: "Nordic Prowear",
    brandSubtitle: "Garment Inventory & B2B CRM",
    language: "Language",
    english: "English (US)",
    norwegian: "Norsk (NO)",

    // Navigation Sidebar & Menus
    dashboard: "Dashboard",
    articles: "Articles",
    sizeCharts: "Article Size Charts",
    products: "Products & Styles",
    categories: "Categories",
    inventory: "Inventory Control",
    stockIn: "Stock In",
    stockOut: "Stock Out",
    transactions: "Transactions",
    crm: "CRM",
    customers: "Customers",
    leads: "Leads",
    allLeads: "All Leads",
    pipeline: "Pipeline",
    leadPipeline: "Lead Pipeline",
    tasks: "Tasks",
    allTasks: "All Tasks",
    taskCalendar: "Task Calendar",
    support: "Support",
    supportTickets: "Support Tickets",
    returns: "Returns",
    lowStock: "Low Stock",
    sales: "Sales & POS",
    b2bOrders: "B2B Customer Orders",
    b2bPortal: "B2B Customer Portal",
    reports: "Reports",
    reportsHub: "Comprehensive Reports & Exports",
    weightCalculator: "Parcel Weight Calculator",
    users: "User Management",
    settings: "Settings",
    logout: "Logout",

    // Common Actions & Controls
    search: "Search...",
    searchPlaceholder: "Search by keyword, SKU, name, or reference...",
    cancel: "Cancel",
    save: "Save",
    saveChanges: "Save Changes",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    details: "Details",
    create: "Create",
    add: "Add",
    addNew: "Add New",
    update: "Update",
    filter: "Filter",
    applyFilters: "Apply Filters",
    resetFilters: "Reset Filters",
    export: "Export",
    exportExcel: "Export to Excel (.xlsx)",
    exportPdf: "Download PDF (.pdf)",
    print: "Print",
    printPdf: "Print PDF",
    close: "Close",
    back: "Back",
    confirm: "Confirm",
    confirmDelete: "Are you sure you want to delete this item?",
    loading: "Loading...",
    submitting: "Submitting...",
    processing: "Processing...",
    success: "Success",
    error: "Error",
    warning: "Warning",
    noData: "No records found",
    actions: "Actions",
    all: "All",
    status: "Status",
    date: "Date",
    notes: "Notes",
    quantity: "Quantity",
    type: "Type",
    previous: "Previous",
    new: "New",
    name: "Name",
    company: "Company",
    contactPerson: "Contact Person",
    user: "User",
    role: "Role",
    email: "Email",
    phone: "Phone",
    address: "Address",
    city: "City",
    postalCode: "Postal Code",
    country: "Country",
    INDIVIDUAL: "Individual",
    BUSINESS: "Business",
    WHOLESALE: "Wholesale B2B",
    VIP: "VIP Client",
    REGULAR: "Regular",
    subtotal: "Subtotal",
    taxMva: "VAT (25% MVA)",
    totalAmount: "Total Amount",
    grandTotal: "Grand Total",
    discount: "Discount",
    unitPrice: "Unit Price",
    purchasePrice: "Purchase Price",
    salePrice: "Sale Price",

    // Status Values & Badges
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    processingStatus: "Processing",
    cancelled: "Cancelled",
    fulfilled: "Fulfilled",
    open: "Open",
    inProgress: "In Progress",
    resolved: "Resolved",
    closed: "Closed",
    high: "High",
    medium: "Medium",
    low: "Low",
    urgent: "Urgent",
    won: "Won",
    lost: "Lost",
    draft: "Draft",
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    PENDING: "Pending",
    COMPLETED: "Completed",
    PROCESSING: "Processing",
    CANCELLED: "Cancelled",
    FULFILLED: "Fulfilled",
    OPEN: "Open",
    IN_PROGRESS: "In Progress",
    RESOLVED: "Resolved",
    CLOSED: "Closed",
    HIGH: "High",
    MEDIUM: "Medium",
    LOW: "Low",
    URGENT: "Urgent",
    DRAFT: "Draft",
    NEW: "New",
    CONTACTED: "Contacted",
    QUALIFIED: "Qualified",
    PROPOSAL_SENT: "Proposal Sent",
    NEGOTIATION: "Negotiation",
    WON: "Won",
    LOST: "Lost",
    STOCK_IN: "Stock In",
    STOCK_OUT: "Stock Out",
    inventoryMovementHistory: "Comprehensive log of inbound, outbound, and adjustment inventory movements",

    // Dashboard Page
    dashboardTitle: "Dashboard",
    dashboardSubtitle: "Nordic Prowear Operational Overview",
    totalArticles: "Total Articles",
    totalProducts: "Total Products",
    totalStock: "Total Stock",
    inventoryValue: "Inventory Value",
    lowStockItems: "Low Stock Items",
    outOfStock: "Out Of Stock",
    completedReturns: "Completed Returns",
    recentTransactions: "Recent Transactions",
    recentReturns: "Recent Returns",
    lowStockProducts: "Low Stock Products",
    stockHealthOverview: "Stock Health Overview",
    openTasksCount: "Open Tasks",
    taskSummaryTitle: "Task Summary",

    // Articles & Products
    articlesTitle: "Articles & Garment Catalog",
    articlesSubtitle: "Manage apparel styles, sizes, colors, and stock levels",
    articlesAndBarcodes: "Articles & Barcodes",
    articlesPageDesc: "Manage apparel products, variants, barcode sheets, and label printing.",
    excelWithBarcodes: "Excel (+ Barcodes)",
    printLabels: "Print Labels",
    addArticle: "Add Article",
    costPriceManager: "Cost Price Manager",
    mixedCarton: "Mixed Carton (Last Box)",
    allStyles: "All Styles",
    variantsLabel: "variants",
    variantLabel: "variant",
    styleFilterLabel: "Style #",
    totalLabel: "total",
    totalTasksLabel: "Total Tasks",
    overdueLabel: "Overdue",
    dueTodayLabel: "Due Today",
    highPriorityLabel: "High Priority",
    pendingLabel: "Pending",
    completedLabel: "Completed",
    addNewArticle: "Add New Article",
    editArticle: "Edit Article",
    articleDetails: "Article Specifications",
    productName: "Product / Style Name",
    sku: "SKU / Item Code",
    barcode: "Barcode",
    category: "Category",
    selectCategory: "Select Category",
    color: "Color",
    size: "Size",
    minStock: "Minimum Stock Alert",
    weightInKg: "Weight (kg)",
    weightPerArticle: "Weight per Article (kg)",
    missingWeightBadge: "Weight Missing",
    fabricComposition: "Fabric Composition",
    fabricWeight: "Fabric Weight (GSM)",
    fabricLabel: "Fabric",
    washingCare: "Washing & Care Instructions",
    availableColors: "Available Garment Colours",
    availableSizes: "Available Sizes in",
    priceRevisionHistory: "Price Revision History",
    printBarcodeBtn: "Print Barcode Labels",
    scanBarcodeBtn: "Scan Barcode",

    // Categories
    categoriesTitle: "Product Categories",
    categoriesSubtitle: "Organize garment styles and workwear segments",
    addNewCategory: "Add New Category",
    editCategory: "Edit Category",
    categoryName: "Category Name",
    categorySlug: "Category Slug",
    categoryDescription: "Description",
    parentCategory: "Parent Category",
    totalItemsInCategory: "Articles in Category",

    // Stock In & Out / Inventory
    stockInTitle: "Stock In & Receiving",
    stockInSubtitle: "Receive finished garments into warehouse storage",
    stockOutTitle: "Stock Out & Shipment Fulfillment",
    stockOutSubtitle: "Dispatch goods and generate official delivery notes",
    transactionsTitle: "Inventory Movement History",
    transactionsSubtitle: "Full audit trail of stock additions, dispatches, and adjustments",
    returnsTitle: "Customer Returns & Restocking",
    returnsSubtitle: "Manage RMA, defective garments, and inventory returns",
    lowStockTitle: "Low Stock Alert Center",
    lowStockSubtitle: "Articles currently below safety stock threshold",
    mandatoryCustomerSelect: "Select Customer (Mandatory)",
    selectCustomerPlaceholder: "-- Choose Customer receiving stock --",
    scanOrSearchProduct: "Scan Barcode or Search SKU / Style...",
    packagingWeightKg: "Packaging Weight (kg)",
    garmentWeightKg: "Total Garment Weight (kg)",
    estimatedParcelWeight: "Estimated Parcel Weight (kg)",
    weightMissingAlert: "Warning: Some selected items do not have weight specified. Total parcel weight may be inaccurate.",
    performStockOut: "Process Stock Out & Generate Delivery Note",
    deliveryNote: "Delivery Note",
    deliveryNoteNumber: "Delivery Note #",
    deliveryNoteHistory: "Stock Out & Delivery Note History",
    reprintDeliveryNote: "Print / Reprint Delivery Note PDF",
    processReturn: "Process Return",
    returnReason: "Reason for Return",
    returnQuantity: "Return Quantity",
    reasonDamaged: "Damaged / Defective",
    reasonWrongSize: "Wrong Size / Color",
    reasonCustomerReturn: "Customer Return",
    reasonExcessStock: "Excess Stock",

    // CRM & Customers
    customerRegister: "Customer Database",
    customerRegisterSubtitle: "Manage B2B client accounts, contacts, and custom pricing",
    addNewCustomer: "Add New Customer",
    registerCustomer: "Add New Customer",
    searchCustomersPlaceholder: "Search by customer name, company, phone, email...",
    allCustomerTypes: "All Customer Types",
    allStatus: "All Statuses",
    individual: "Individual",
    business: "Business",
    suspended: "Suspended",
    editCustomer: "Edit Customer",
    customerDetails: "Customer Profile & CRM Details",
    customerCode: "Customer ID",
    fullName: "Contact Name",
    companyName: "Company Name",
    vatNumber: "VAT / Org Number",
    customerType: "Customer Type",
    regular: "Regular",
    wholesale: "Wholesale B2B",
    vip: "VIP Client",
    totalOrders: "Total Orders",
    totalSpent: "Total Spent",
    contacts: "Contacts & People",
    addContact: "Add Contact",
    primaryContact: "Primary Contact",
    customPricing: "Customer-Specific Pricing",
    customPriceNotice: "Override default sale price for this specific customer:",
    catalogAccess: "Product Catalog Permissions",
    catalogPermissionNotice: "Control which articles this customer can view & order in their portal:",
    portalAccess: "B2B Portal Access & Password",
    setPortalPassword: "Set Customer Portal Password",
    gdprActions: "GDPR Compliance Data Management",
    exportGdpr: "Export Customer GDPR File",
    anonymizeGdpr: "Anonymize Customer (Right to be Forgotten)",
    saveCustomer: "Save Customer",
    tabOverview: "Overview",
    tabContacts: "Contacts",
    tabOrders: "Orders",
    tabStockOut: "Dispatches & Delivery Notes",
    tabGdpr: "GDPR & Privacy",

    // Leads & Pipeline
    leadsTitle: "B2B Leads & Prospecting",
    leadsSubtitle: "Track new sales inquiries and business opportunities",
    leadPipelineTitle: "Sales Pipeline",
    leadPipelineSubtitle: "Visual drag-and-drop opportunity tracking stages",
    addNewLead: "Add New Lead",
    editLead: "Edit Lead",
    leadDetails: "Lead Details & Activity",
    leadTitle: "Lead Title / Opportunity",
    leadValue: "Estimated Deal Value (NOK)",
    leadStage: "Pipeline Stage",
    stageNew: "New Inquiry",
    stageContacted: "Contacted",
    stageQualified: "Qualified",
    stageProposal: "Proposal Sent",
    stageNegotiation: "Negotiation",
    stageWon: "Won (Deal Closed)",
    stageLost: "Lost",
    priority: "Priority",
    assignLead: "Assign Sales Rep",
    assignedTo: "Assigned To",
    leadSource: "Lead Source",
    leadRank: "Rank",
    legalEntity: "Legal Entity",
    leadSegment: "Industry / Segment",
    contactType: "Contact Type",
    verificationStatus: "Verification Status",
    revenueMnok: "Turnover (MNOK)",
    financialYear: "Financial Year",
    revenueBasis: "Revenue Basis",
    county: "County",
    relevantStaff: "Relevant Staff / Departments",
    relevantTextiles: "Relevant Textiles & Services",
    healthcareNvk: "Healthcare / NVK Member",
    recommendedContact: "Recommended Contact Person",
    allSegments: "All Segments",
    allPriorities: "All Priorities",
    allCounties: "All Counties",
    activityTimeline: "Activity Timeline & History",
    logActivity: "Log Activity",
    sendEmail: "Send Email",
    emailSubject: "Subject",
    emailMessage: "Message body...",

    // Tasks
    tasksTitle: "Task Management",
    tasksSubtitle: "Assign, organize, and track team assignments and deadlines",
    addNewTask: "Create New Task",
    editTask: "Edit Task",
    taskDetails: "Task Details",
    taskTitle: "Task Title",
    dueDate: "Due Date",
    taskPriority: "Priority",
    taskAssignee: "Assignee",
    markComplete: "Mark as Completed",
    taskCalendarTitle: "Task Schedule & Calendar",

    // Support Tickets
    supportTitle: "Customer Support Tickets",
    supportSubtitle: "Manage inbound inquiries, warranty, and customer issues",
    createTicket: "Create Support Ticket",
    ticketDetails: "Support Ticket Details",
    ticketSubject: "Subject",
    ticketCategory: "Category",
    categoryBilling: "Billing & Invoicing",
    categoryOrderIssue: "Order / Shipment Issue",
    categoryDefect: "Product Quality / Defect",
    categoryGeneral: "General Inquiries",
    ticketPriority: "Ticket Priority",
    assignAgent: "Assign Agent",
    ticketMessages: "Conversation & Message Thread",
    reply: "Reply",
    resolveTicket: "Mark as Resolved",
    closeTicket: "Close Ticket",

    // Reports Hub & Analytics
    reportsHubTitle: "Comprehensive Reports & Analytics",
    reportsHubSubtitle: "Export data, analyze revenue, and monitor inventory movements",
    tabReportOverview: "Overview",
    tabReportLeads: "Lead Analytics",
    tabReportCustomers: "Customer Analytics",
    tabReportRevenue: "Revenue Analytics",
    reportInventory: "Inventory Report",
    reportStockIn: "Stock In Report",
    reportStockOut: "Stock Out Report",
    reportCustomerOrders: "Customer Orders Report",
    reportProductMovement: "Product Movement Report",
    reportLowStock: "Low Stock Report",
    reportCustomerPurchases: "Customer Purchase Report",
    reportOpenOrders: "Open Orders Report",
    fromDate: "From Date",
    toDate: "To Date",
    totalRevenue: "Total Revenue",
    conversionRate: "Lead Conversion Rate",
    averageOrderValue: "Average Order Value",
    topArticles: "Top Selling Articles",
    topCustomers: "Top B2B Customers",

    // Sales & B2B Admin Orders
    salesTitle: "Sales & POS Invoicing",
    salesSubtitle: "Direct store billing and invoice generation",
    newSale: "New Direct Sale",
    saleDetails: "Sale Invoice Details",
    invoiceNumber: "Invoice #",
    paymentMethod: "Payment Method",
    methodCash: "Cash",
    methodCard: "Credit / Debit Card",
    methodBankTransfer: "Bank Transfer",
    methodInvoice: "B2B Invoice (Net 30)",
    b2bAdminOrdersTitle: "B2B Customer Orders Management",
    b2bAdminOrdersSubtitle: "Review, approve, and fulfill orders submitted via Customer Portal",
    fulfillOrderBtn: "Fulfill & Process Stock Out",
    orderNumber: "Order #",

    // B2B Customer Portal
    b2bCatalog: "B2B Product Catalogue",
    addToCart: "Add to Cart",
    cartSummary: "Shopping Cart Summary",
    shippingAddress: "Shipping Address",
    orderNotes: "Order Notes / References",
    placeOrder: "Place B2B Order",
    orderConfirmation: "Order Confirmation",
    orderHistory: "Customer Order History",
    parcelWeightCalculator: "Shipment Weight Estimator",
    customerOrderInfo: "Customer Order Information",
    autoFetchedProfile: "Auto-Fetched Profile",
    staffAdminMode: "Staff Admin Mode",
    selectCustomerAccount: "Select Customer Account (Dropdown):",
    useProfileDefault: "Use profile default",
    autoFilledEditable: "Auto-filled • Editable",
    addressPreFilledNote: "Address pre-filled from customer file. You can freely edit or update it.",

    // Users & Settings
    usersTitle: "User & Staff Management",
    usersSubtitle: "Manage administrative logins, permissions, and roles",
    addNewUser: "Add New User",
    editUser: "Edit User",
    userName: "Full Name",
    userRole: "System Role",
    roleAdmin: "Administrator",
    roleStaff: "Staff Member",
    roleCustomer: "B2B Customer",
    settingsTitle: "System Settings",
    settingsSubtitle: "Configure company details, language defaults, and system preferences",
    tabProfileSettings: "My Profile",
    tabStoreSettings: "Store & Brand",
    tabNotificationSettings: "Notifications",

    // Login & Auth
    loginHeaderTitle: "Nordic Prowear",
    loginHeaderSubtitle: "Garment Inventory, CRM & B2B Portal",
    staffLoginTab: "Staff Login",
    customerLoginTab: "B2B Customer Login",
    customerRegisterTab: "Self-Service Sign Up",
    emailOrPhone: "Email or Phone Number",
    password: "Password",
    loginButton: "Sign In",
    loggingIn: "Signing in...",
    customerLoginSubtext: "Access your customer-specific B2B catalog & order history.",
    contactPersonName: "Contact Person Name",
    streetAddress: "Street Address",
    cityPostal: "City / Postal Code",
    createAccountBtn: "Create Account & Browse Catalog",
    googleAuthBtn: "Continue with Google (SSO)",
    forgotPasswordText: "Forgot your password?",
  },

  no: {
    // Brand & App Header
    brandTitle: "Nordic Prowear",
    brandSubtitle: "Kleslager & B2B CRM",
    language: "Språk",
    english: "English (US)",
    norwegian: "Norsk (NO)",

    // Navigation Sidebar & Menus
    dashboard: "Oversikt",
    articles: "Artikler",
    products: "Produkter og stiler",
    categories: "Kategorier",
    inventory: "Lagerstyring",
    stockIn: "Varemottak (Stock In)",
    stockOut: "Vareutgang (Stock Out)",
    transactions: "Transaksjoner",
    crm: "CRM",
    customers: "Kunder",
    leads: "Leads",
    allLeads: "Alle leads",
    pipeline: "Pipeline",
    leadPipeline: "Salgs-pipeline",
    tasks: "Oppgaver",
    allTasks: "Alle oppgaver",
    taskCalendar: "Oppgavekalender",
    support: "Support",
    supportTickets: "Support-saker",
    returns: "Returer",
    lowStock: "Lavt lager",
    sales: "Salg & POS",
    b2bOrders: "B2B Kundebestillinger",
    b2bPortal: "B2B Kundeportal",
    reports: "Rapporter",
    reportsHub: "Komplette rapporter og eksport",
    weightCalculator: "Pakkevekt-beregner",
    users: "Brukerhåndtering",
    settings: "Innstillinger",
    logout: "Logg ut",

    // Common Actions & Controls
    search: "Søk...",
    searchPlaceholder: "Søk etter nøkkelord, SKU, navn eller referanse...",
    cancel: "Avbryt",
    save: "Lagre",
    saveChanges: "Lagre endringer",
    delete: "Slett",
    edit: "Rediger",
    view: "Vis",
    details: "Detaljer",
    create: "Opprett",
    add: "Legg til",
    addNew: "Legg til ny",
    update: "Oppdater",
    filter: "Filtrer",
    applyFilters: "Bruk filtre",
    resetFilters: "Tilbakestill filtre",
    export: "Eksporter",
    exportExcel: "Eksporter til Excel (.xlsx)",
    exportPdf: "Last ned PDF (.pdf)",
    print: "Skriv ut",
    printPdf: "Skriv ut PDF",
    close: "Lukk",
    back: "Tilbake",
    confirm: "Bekreft",
    confirmDelete: "Er du sikker på at du vil slette dette elementet?",
    loading: "Laster...",
    submitting: "Sender inn...",
    processing: "Behandler...",
    success: "Suksess",
    error: "Feil",
    warning: "Advarsel",
    noData: "Ingen data funnet",
    actions: "Handlinger",
    all: "Alle",
    status: "Status",
    date: "Dato",
    notes: "Notater",
    quantity: "Antall",
    type: "Type",
    previous: "Forrige",
    new: "Ny",
    name: "Navn",
    company: "Bedrift",
    contactPerson: "Kontaktperson",
    user: "Bruker",
    role: "Rolle",
    email: "E-post",
    phone: "Telefon",
    address: "Adresse",
    city: "Poststed/By",
    postalCode: "Postnummer",
    country: "Land",
    INDIVIDUAL: "Privatkunde",
    BUSINESS: "Bedriftskunde",
    WHOLESALE: "Engros B2B",
    VIP: "VIP-kunde",
    REGULAR: "Ordinær",
    subtotal: "Nettobeløp",
    taxMva: "MVA (25%)",
    totalAmount: "Totalbeløp",
    grandTotal: "Totalbeløp inkl. MVA",
    discount: "Rabatt",
    unitPrice: "Enhetspris",
    purchasePrice: "Innkjøpspris",
    salePrice: "Salgspris",

    // Status Values & Badges
    active: "Aktiv",
    inactive: "Inaktiv",
    pending: "Avventer",
    completed: "Fullført",
    processingStatus: "Under behandling",
    cancelled: "Kansellert",
    fulfilled: "Levert",
    open: "Åpen",
    inProgress: "Pågår",
    resolved: "Løst",
    closed: "Lukket",
    high: "Høy",
    medium: "Middels",
    low: "Lav",
    urgent: "Haster",
    won: "Vunnet",
    lost: "Tapt",
    draft: "Utkast",
    ACTIVE: "Aktiv",
    INACTIVE: "Inaktiv",
    PENDING: "Avventer",
    COMPLETED: "Fullført",
    PROCESSING: "Under behandling",
    CANCELLED: "Kansellert",
    FULFILLED: "Levert",
    OPEN: "Åpen",
    IN_PROGRESS: "Pågår",
    RESOLVED: "Løst",
    CLOSED: "Lukket",
    HIGH: "Høy",
    MEDIUM: "Middels",
    LOW: "Lav",
    URGENT: "Haster",
    DRAFT: "Utkast",
    NEW: "Ny",
    CONTACTED: "Kontaktet",
    QUALIFIED: "Kvalifisert",
    PROPOSAL_SENT: "Tilbud sendt",
    NEGOTIATION: "Forhandling",
    WON: "Vunnet",
    LOST: "Tapt",
    STOCK_IN: "Varemottak",
    STOCK_OUT: "Vareutgang",
    inventoryMovementHistory: "Komplett logg over varemottak, utsendelser og korrigeringer",

    // Dashboard Page
    dashboardTitle: "Oversikt",
    dashboardSubtitle: "Nordic Prowear Operativ Oversikt",
    totalArticles: "Totalt artikler",
    totalProducts: "Totalt produkter",
    totalStock: "Totalt på lager",
    inventoryValue: "Lagerverdi",
    lowStockItems: "Artikler med lavt lager",
    outOfStock: "Tomt på lager",
    completedReturns: "Fullførte returer",
    recentTransactions: "Nylige transaksjoner",
    recentReturns: "Nylige returer",
    lowStockProducts: "Lavt lager-produkter",
    stockHealthOverview: "Lagerbeholdningsstatus",
    openTasksCount: "Åpne oppgaver",
    taskSummaryTitle: "Oppgavesammendrag",

    // Articles & Products
    articles: "Artikler",
    sizeCharts: "Artikkel Måleskjema",
    articlesTitle: "Artikler & Kleskatalog",
    articlesSubtitle: "Administrer klesstiler, størrelser, farger og lagerbeholdning",
    articlesAndBarcodes: "Artikler og strekkoder",
    articlesPageDesc: "Administrer klesprodukter, varianter, strekkodeark og etikettutskrift.",
    excelWithBarcodes: "Excel (+ Strekkoder)",
    printLabels: "Skriv ut etiketter",
    addArticle: "Legg til artikkel",
    costPriceManager: "Kostpriser & Kalkulator",
    mixedCarton: "Blandet kartong (Rest)",
    allStyles: "Alle stiler",
    variantsLabel: "varianter",
    variantLabel: "variant",
    styleFilterLabel: "Stil #",
    totalLabel: "totalt",
    totalTasksLabel: "Totalt antall oppgaver",
    overdueLabel: "Forfalte",
    dueTodayLabel: "Forfaller i dag",
    highPriorityLabel: "Høy prioritet",
    pendingLabel: "Avventer",
    completedLabel: "Fullført",
    addNewArticle: "Legg til ny artikkel",
    editArticle: "Rediger artikkel",
    articleDetails: "Artikkelspesifikasjoner",
    productName: "Produkt- / Stilnavn",
    sku: "SKU / Varenummer",
    barcode: "Strekkode",
    category: "Kategori",
    selectCategory: "Velg kategori",
    color: "Farge",
    size: "Størrelse",
    minStock: "Varsel ved minimumslager",
    weightInKg: "Vekt (kg)",
    weightPerArticle: "Vekt per artikkel (kg)",
    missingWeightBadge: "Vekt mangler",
    fabricComposition: "Stoffsammensetning",
    fabricWeight: "Stoffvekt (GSM)",
    fabricLabel: "Stoff",
    washingCare: "Vaskeanvisning & Vedlikehold",
    availableColors: "Tilgjengelige farger",
    availableSizes: "Tilgjengelige størrelser i",
    priceRevisionHistory: "Prisendringshistorikk",
    printBarcodeBtn: "Skriv ut strekkoder",
    scanBarcodeBtn: "Skann strekkode",

    // Categories
    categoriesTitle: "Produktkategorier",
    categoriesSubtitle: "Strukturer kleskolleksjoner og arbeidstøy-segmenter",
    addNewCategory: "Legg til ny kategori",
    editCategory: "Rediger kategori",
    categoryName: "Kategorinavn",
    categorySlug: "Kategori-kortnavn (Slug)",
    categoryDescription: "Beskrivelse",
    parentCategory: "Hovedkategori",
    totalItemsInCategory: "Artikler i kategorien",

    // Stock In & Out / Inventory
    stockInTitle: "Varemottak (Stock In)",
    stockInSubtitle: "Registrer innkommende varer og produksjon på lager",
    stockOutTitle: "Vareutgang & Forsendelse (Stock Out)",
    stockOutSubtitle: "Send varer ut og opprett offisielle følgesedler",
    transactionsTitle: "Historikk for lagerbevegelser",
    transactionsSubtitle: "Komplett logg over varemottak, utsendelser og korrigeringer",
    returnsTitle: "Kundereturer & Restlager",
    returnsSubtitle: "Håndter returer, reklamasjoner og lagerjusteringer",
    lowStockTitle: "Varslingssenter for lavt lager",
    lowStockSubtitle: "Artikler som er under fastsatt sikkerhetslager",
    mandatoryCustomerSelect: "Velg kunde (Obligatorisk)",
    selectCustomerPlaceholder: "-- Velg kunden som mottar varene --",
    scanOrSearchProduct: "Skann strekkode eller søk SKU / stil...",
    packagingWeightKg: "Emballasjevekt (kg)",
    garmentWeightKg: "Total klesvekt (kg)",
    estimatedParcelWeight: "Beregnet pakkevekt (kg)",
    weightMissingAlert: "Advarsel: Noen valgte artikler mangler vekt. Total pakkevekt kan være unøyaktig.",
    performStockOut: "Registrer vareutgang og opprett følgeseddel",
    deliveryNote: "Følgeseddel",
    deliveryNoteNumber: "Følgeseddel #",
    deliveryNoteHistory: "Historikk for vareutgang og følgesedler",
    reprintDeliveryNote: "Skriv ut / Utskrift av følgeseddel PDF",
    processReturn: "Behandle retur",
    returnReason: "Årsak til retur",
    returnQuantity: "Returantall",
    reasonDamaged: "Skadet / Defekt vare",
    reasonWrongSize: "Feil størrelse / farge",
    reasonCustomerReturn: "Kunderetur",
    reasonExcessStock: "Overskuddslager",

    // CRM & Customers
    customerRegister: "Kundedatabase",
    customerRegisterSubtitle: "Administrer B2B-kundekontoer, kontakter og spesialpriser",
    addNewCustomer: "Legg til ny kunde",
    registerCustomer: "Legg til ny kunde",
    searchCustomersPlaceholder: "Søk etter kundenavn, bedrift, telefon, e-post...",
    allCustomerTypes: "Alle kundetyper",
    allStatus: "Alle statuser",
    individual: "Privatkunde",
    business: "Bedriftskunde",
    suspended: "Suspendert",
    editCustomer: "Rediger kunde",
    customerDetails: "Kundeprofil & CRM-detaljer",
    customerCode: "Kundenummer",
    fullName: "Kontaktperson",
    companyName: "Bedriftsnavn",
    vatNumber: "Organisasjonsnummer (MVA)",
    customerType: "Kundetype",
    regular: "Ordinær",
    wholesale: "Engros B2B",
    vip: "VIP-kunde",
    totalOrders: "Totalt antall ordrer",
    totalSpent: "Totalt handlet for",
    contacts: "Kontakter og personer",
    addContact: "Legg til kontakt",
    primaryContact: "Hovedkontakt",
    customPricing: "Kundespesifikke priser",
    customPriceNotice: "Overstyr standard salgspris for denne spesifikke kunden:",
    catalogAccess: "Produktkatalog-tilganger",
    catalogPermissionNotice: "Styr hvilke artikler denne kunden kan se og bestille i sin portal:",
    portalAccess: "B2B Portal-tilgang og passord",
    setPortalPassword: "Angi passord for kundeportal",
    gdprActions: "GDPR Personvern & Datahåndtering",
    exportGdpr: "Eksporter GDPR-datafil",
    anonymizeGdpr: "Anonymiser kunde (Rett til å bli glemt)",
    saveCustomer: "Lagre kunde",
    tabOverview: "Oversikt",
    tabContacts: "Kontakter",
    tabOrders: "Ordrer",
    tabStockOut: "Utsendelser & Følgesedler",
    tabGdpr: "GDPR & Personvern",

    // Leads & Pipeline
    leadsTitle: "B2B Leads & Prospektering",
    leadsSubtitle: "Følg opp nye salgshenvendelser og forretningsmuligheter",
    leadPipelineTitle: "Salgs-pipeline",
    leadPipelineSubtitle: "Visuell dra-og-slipp oppfølging av salgsmuligheter",
    addNewLead: "Legg til nytt lead",
    editLead: "Rediger lead",
    leadDetails: "Lead-detaljer & Aktivitet",
    leadTitle: "Lead tittel / Mulighet",
    leadValue: "Estimert avtaleverdi (NOK)",
    leadStage: "Pipeline-fase",
    stageNew: "Ny henvendelse",
    stageContacted: "Kontaktet",
    stageQualified: "Kvalifisert",
    stageProposal: "Tilbud sendt",
    stageNegotiation: "Forhandling",
    stageWon: "Vunnet (Avtale inngått)",
    stageLost: "Tapt",
    priority: "Prioritet",
    assignLead: "Tildel selger",
    assignedTo: "Tildelt",
    leadSource: "Lead-kilde",
    leadRank: "Rangering",
    legalEntity: "Juridisk enhet",
    leadSegment: "Bransje / Segment",
    contactType: "Kontakttype",
    verificationStatus: "Verifiseringsstatus",
    revenueMnok: "Omsetning (MNOK)",
    financialYear: "Regnskapsår",
    revenueBasis: "Omsetningsgrunnlag",
    county: "Fylke",
    relevantStaff: "Målgruppe / Avdelinger",
    relevantTextiles: "Relevante tekstiler & tjenester",
    healthcareNvk: "Helse / NVK-medlem",
    recommendedContact: "Anbefalt kontaktperson",
    allSegments: "Alle bransjer",
    allPriorities: "Alle prioriteter",
    allCounties: "Alle fylker",
    activityTimeline: "Aktivitetstidslinje & Historikk",
    logActivity: "Loggfør aktivitet",
    sendEmail: "Send e-post",
    emailSubject: "Emne",
    emailMessage: "Meldingsinnhold...",

    // Tasks
    tasksTitle: "Oppgavehåndtering",
    tasksSubtitle: "Tildel, organiser og følg opp teamets oppgaver og tidsfrister",
    addNewTask: "Opprett ny oppgave",
    editTask: "Rediger oppgave",
    taskDetails: "Oppgavedetaljer",
    taskTitle: "Oppgavetittel",
    dueDate: "Frist",
    taskPriority: "Prioritet",
    taskAssignee: "Ansvarlig",
    markComplete: "Marker som fullført",
    taskCalendarTitle: "Oppgaveplan & Kalender",

    // Support Tickets
    supportTitle: "Kundestøtte & Support-saker",
    supportSubtitle: "Håndter henvendelser, garantisaker og kundespørsmål",
    createTicket: "Opprett support-sak",
    ticketDetails: "Support-sak detaljer",
    ticketSubject: "Emne",
    ticketCategory: "Kategori",
    categoryBilling: "Faktura & Betaling",
    categoryOrderIssue: "Ordre- / Forsendelsesproblem",
    categoryDefect: "Produktfeil / Reklamasjon",
    categoryGeneral: "Generelle henvendelser",
    ticketPriority: "Saksprioritet",
    assignAgent: "Tildel saksbehandler",
    ticketMessages: "Samtale- og meldingstråd",
    reply: "Svar",
    resolveTicket: "Marker som løst",
    closeTicket: "Lukk sak",

    // Reports Hub & Analytics
    reportsHubTitle: "Komplette rapporter og analyser",
    reportsHubSubtitle: "Eksporter data, analyser inntekter og følg lagerbevegelser",
    tabReportOverview: "Oversikt",
    tabReportLeads: "Lead-analyse",
    tabReportCustomers: "Kundeanalyse",
    tabReportRevenue: "Inntektsanalyse",
    reportInventory: "Lagerrapport",
    reportStockIn: "Varemottaksrapport",
    reportStockOut: "Vareutgangsrapport",
    reportCustomerOrders: "Kundeordrerapport",
    reportProductMovement: "Produktbevegelsesrapport",
    reportLowStock: "Lavt lager-rapport",
    reportCustomerPurchases: "Kunderapport (Kjøp)",
    reportOpenOrders: "Åpne ordrer-rapport",
    fromDate: "Fra dato",
    toDate: "Til dato",
    totalRevenue: "Total omsetning",
    conversionRate: "Konverteringsrate",
    averageOrderValue: "Gjennomsnittlig ordreverdi",
    topArticles: "Mest solgte artikler",
    topCustomers: "Største B2B-kunder",

    // Sales & B2B Admin Orders
    salesTitle: "Salg & POS-kasse",
    salesSubtitle: "Direkte butikksalg og fakturering",
    newSale: "Nytt direktesalg",
    saleDetails: "Salgsfaktura detaljer",
    invoiceNumber: "Faktura #",
    paymentMethod: "Betalingsmåte",
    methodCash: "Kontant",
    methodCard: "Bankkort / Kredittkort",
    methodBankTransfer: "Bankoverføring",
    methodInvoice: "B2B Faktura (30 dager)",
    b2bAdminOrdersTitle: "Håndtering av B2B-kundebestillinger",
    b2bAdminOrdersSubtitle: "Godkjenn, behandle og send ut bestillinger fra kundeportalen",
    fulfillOrderBtn: "Fullfør ordre og trekk fra lager",
    orderNumber: "Ordrenummer #",

    // B2B Customer Portal
    b2bCatalog: "B2B Produktkatalog",
    addToCart: "Legg i handlekurv",
    cartSummary: "Sammendrag av handlekurv",
    shippingAddress: "Leveringsadresse",
    orderNotes: "Ordrenotater / Referanse",
    placeOrder: "Send B2B-bestilling",
    orderConfirmation: "Ordrebekreftelse",
    orderHistory: "Kundeordrehistorikk",
    parcelWeightCalculator: "Forsendelsesvekt-kalkulator",
    customerOrderInfo: "Kundeopplysninger for ordre",
    autoFetchedProfile: "Automatisk hentet profil",
    staffAdminMode: "Ansatt / Admin-modus",
    selectCustomerAccount: "Velg B2B-konto / Bedrift (Rullegardin):",
    useProfileDefault: "Bruk profiladresse",
    autoFilledEditable: "Automatisk utfylt • Kan endres",
    addressPreFilledNote: "Adressen er forhåndsutfylt fra kundekortet. Du kan fritt redigere den.",

    // Users & Settings
    usersTitle: "Bruker- og ansatthåndtering",
    usersSubtitle: "Administrer innlogginger, tilganger og roller for ansatte",
    addNewUser: "Legg til ny bruker",
    editUser: "Rediger bruker",
    userName: "Fullt navn",
    userRole: "Systemrolle",
    roleAdmin: "Administrator",
    roleStaff: "Ansatt",
    roleCustomer: "B2B Kunde",
    settingsTitle: "Systeminnstillinger",
    settingsSubtitle: "Konfigurer bedriftsopplysninger, standardspråk og systemvalg",
    tabProfileSettings: "Min profil",
    tabStoreSettings: "Bedrift & Merkevare",
    tabNotificationSettings: "Varslinger",

    // Login & Auth
    loginHeaderTitle: "Nordic Prowear",
    loginHeaderSubtitle: "Kleslager, CRM og B2B-portal",
    staffLoginTab: "Ansatt-innlogging",
    customerLoginTab: "B2B Kundeportal-innlogging",
    customerRegisterTab: "Bli B2B-kunde (Selvbetjening)",
    emailOrPhone: "E-post eller telefonnummer",
    password: "Passord",
    loginButton: "Logg inn",
    loggingIn: "Logger inn...",
    customerLoginSubtext: "Få tilgang til din kundespesifikke B2B-katalog og ordrehistorikk.",
    contactPersonName: "Kontaktperson",
    streetAddress: "Leveringsadresse (Gateadresse)",
    cityPostal: "Poststed / By",
    createAccountBtn: "Opprett konto og åpne katalog",
    googleAuthBtn: "Fortsett med Google (SSO)",
    forgotPasswordText: "Glemt passordet ditt?",
  }
};

// Common direct phrases dictionary for automated translation of literal texts
const phraseDictNo = {
  // Navigation & tabs
  "Dashboard": "Oversikt",
  "Articles": "Artikler",
  "Products & Styles": "Produkter og stiler",
  "Categories": "Kategorier",
  "Inventory": "Lagerstyring",
  "Inventory Control": "Lagerstyring",
  "Stock In": "Varemottak (Stock In)",
  "Stock Out": "Vareutgang (Stock Out)",
  "Transactions": "Transaksjoner",
  "CRM": "CRM",
  "Customers": "Kunder",
  "Leads": "Leads",
  "All Leads": "Alle leads",
  "Pipeline": "Pipeline",
  "Tasks": "Oppgaver",
  "All Tasks": "Alle oppgaver",
  "Task Calendar": "Oppgavekalender",
  "Support": "Support",
  "Support Tickets": "Support-saker",
  "Returns": "Returer",
  "Low Stock": "Lavt lager",
  "Sales & POS": "Salg & POS",
  "B2B Customer Orders": "B2B Kundebestillinger",
  "B2B Customer Portal": "B2B Kundeportal",
  "Reports": "Rapporter",
  "Overview": "Oversikt",
  "Lead Analytics": "Lead-analyse",
  "Customer Analytics": "Kundeanalyse",
  "Revenue Analytics": "Inntektsanalyse",
  "User Management": "Brukerhåndtering",
  "Settings": "Innstillinger",
  "Logout": "Logg ut",

  // KPI & Metrics & Tasks
  "Total Tasks": "Totalt antall oppgaver",
  "Pending": "Avventer",
  "Completed": "Fullført",
  "Overdue": "Forfalte",
  "Due Today": "Forfaller i dag",
  "High Priority": "Høy prioritet",
  "Total Articles": "Totalt artikler",
  "Total Products": "Totalt produkter",
  "Total Stock": "Totalt på lager",
  "Inventory Value": "Lagerverdi",
  "Low Stock Items": "Lavt lager-artikler",
  "Out Of Stock": "Tomt på lager",
  "Completed Returns": "Fullførte returer",
  "Recent Transactions": "Nylige transaksjoner",
  "Recent Returns": "Nylige returer",
  "Low Stock Products": "Lavt lager-produkter",
  "Stock Health": "Lagerbeholdningsstatus",
  "Total Revenue": "Total omsetning",
  "Conversion Rate": "Konverteringsrate",
  "Average Order Value": "Gjennomsnittlig ordreverdi",
  "Open Tasks": "Åpne oppgaver",
  "Total Orders": "Totalt antall ordrer",
  "Total Spent": "Totalt handlet for",

  // Articles & Barcodes Page
  "Articles & Barcodes": "Artikler og strekkoder",
  "Manage apparel products, variants, barcode sheets, and label printing.": "Administrer klesprodukter, varianter, strekkodeark og etikettutskrift.",
  "Excel (+ Barcodes)": "Excel (+ Strekkoder)",
  "Print Labels": "Skriv ut etiketter",
  "Add Article": "Legg til artikkel",
  "Add New Article": "Legg til ny artikkel",
  "Search by style no, name, article, SKU, or barcode...": "Søk etter stilnr, navn, artikkel, SKU eller strekkode...",
  "All Styles": "Alle stiler",
  "variant": "variant",
  "variants": "varianter",
  "total": "totalt",
  "Delete Article": "Slett artikkel",
  "Loading apparel articles...": "Laster klesartikler...",
  "No articles found": "Ingen artikler funnet",
  "Try adjusting your search terms or add a new apparel article to get started.": "Prøv å justere søket eller legg til en ny artikkel for å komme i gang.",
  "In Stock": "På lager",
  "Low Stock": "Lavt lager",
  "Garment": "Plagg",
  "Style No": "Stilnr",
  "Article & Color": "Artikkel og farge",
  "Stock": "Lager",
  "Price": "Pris",
  "Click to view garment colors & details": "Klikk for å se farger og detaljer",
  "View Article & Color Options": "Vis artikkel og farger",
  "Article Barcode": "Artikkelstrekkode",
  "Edit Article": "Rediger artikkel",
  "Print Barcodes": "Skriv ut strekkoder",
  "Print Barcode Labels": "Skriv ut strekkodeetiketter",
  "Print Barcode Labels (All Articles)": "Skriv ut strekkoder (Alle artikler)",
  "Individual Labels (Hangtags / Stickers)": "Enkeltetiketter (Hengelapper / Klistremerker)",
  "Mixed Carton Packing Label (Last Box)": "Blandet eske-etikett (Siste eske)",
  "Label Template": "Etikettmal",
  "Copies Mode": "Antall kopier",
  "Single (1 per variant)": "Enkel (1 per variant)",
  "Match On-Hand Stock Qty": "Matcher lagerbeholdning",
  // Product Details & Specifications
  "Active Variant Style No": "Aktiv variant-stilnr",
  "Base Style No": "Hovedstilnr (Base)",
  "Style Name": "Stilnavn",
  "Article / Item": "Artikkel / Vare",
  "Product Name": "Produktnavn",
  "Primary Barcode": "Hovedstrekkode",
  "Colour Code": "Fargekode",
  "Fabric Composition": "Stoffsammensetning",
  "Fabric Weight": "Stoffvekt",
  "Stock Quantity": "Lagerbeholdning",
  "Min Stock Alert": "Minimumslager-varsel",
  "Full Article Specifications": "Komplette artikkelspesifikasjoner",
  "Price Revision History": "Prisendringshistorikk",
  "Old Price": "Gammel pris",
  "New Price": "Ny pris",
  "Changed By": "Endret av",
  "Print Single Sticker": "Skriv ut enkeltetikett",
  "Barcode Label": "Strekkodeetikett",
  "Available Garment Colours": "Tilgjengelige farger",
  "Click a colour option to view garment pictures and available size variants.": "Klikk på en farge for å se plaggbilder og tilgjengelige størrelser.",
  "Select a size to view its exact SKU, Code128 Barcode, and stock level.": "Velg en størrelse for å se nøyaktig SKU, Code128 strekkode og lagerbeholdning.",
  "units": "stk",
  "in stock": "på lager",
  "Sizes": "Størrelser",
  "Add Customer": "Legg til kunde",
  "Add New Customer": "Legg til ny kunde",
  "Add Lead": "Legg til lead",
  "Add New Lead": "Legg til nytt lead",
  "Add Task": "Legg til oppgave",
  "Add New Task": "Legg til ny oppgave",
  "Add Category": "Legg til kategori",
  "Add New Category": "Legg til ny kategori",
  "Create Ticket": "Opprett support-sak",
  "Save": "Lagre",
  "Save Changes": "Lagre endringer",
  "Cancel": "Avbryt",
  "Delete": "Slett",
  "Edit": "Rediger",
  "View": "Vis",
  "Details": "Detaljer",
  "Search...": "Søk...",
  "Search": "Søk",
  "Filter": "Filtrer",
  "Apply Filters": "Bruk filtre",
  "Reset Filters": "Tilbakestill filtre",
  "Export": "Eksporter",
  "Print": "Skriv ut",
  "Print PDF": "Skriv ut PDF",
  "Print Barcode": "Skriv ut strekkoder",
  "Scan Barcode": "Skann strekkode",
  "Back": "Tilbake",
  "Close": "Lukk",
  "Actions": "Handlinger",
  "Status": "Status",
  "Date": "Dato",
  "Notes": "Notater",
  "Quantity": "Antall",
  "Qty": "Antall",
  "Price": "Pris",
  "Unit Price": "Enhetspris",
  "Sale Price": "Salgspris",
  "Purchase Price": "Innkjøpspris",
  "Total Price": "Totalpris",
  "Total Amount": "Totalbeløp",
  "Subtotal": "Nettobeløp",
  "VAT (25%)": "MVA (25%)",
  "Grand Total": "Totalbeløp inkl. MVA",
  "Discount": "Rabatt",
  "Product": "Produkt",
  "SKU": "SKU",
  "Barcode": "Strekkode",
  "Category": "Kategori",
  "Color": "Farge",
  "Size": "Størrelse",
  "Fabric": "Stoff",
  "Weight (kg)": "Vekt (kg)",
  "Min Stock": "Minimumslager",

  // Statuses
  "ACTIVE": "Aktiv",
  "INACTIVE": "Inaktiv",
  "PENDING": "Avventer",
  "COMPLETED": "Fullført",
  "PROCESSING": "Behandles",
  "CANCELLED": "Kansellert",
  "FULFILLED": "Levert",
  "OPEN": "Åpen",
  "IN_PROGRESS": "Pågår",
  "RESOLVED": "Løst",
  "CLOSED": "Lukket",
  "HIGH": "Høy",
  "MEDIUM": "Middels",
  "LOW": "Lav",
  "URGENT": "Haster",
  "WON": "Vunnet",
  "LOST": "Tapt",
  "DRAFT": "Utkast",
  "STOCK_IN": "Varemottak",
  "STOCK_OUT": "Vareutgang",
  "RETURN": "Retur",
  "Active": "Aktiv",
  "Inactive": "Inaktiv",
  "Pending": "Avventer",
  "Completed": "Fullført",
  "Processing": "Behandles",
  "Cancelled": "Kansellert",
  "Fulfilled": "Levert",
  "Open": "Åpen",
  "In Progress": "Pågår",
  "Resolved": "Løst",
  "Closed": "Lukket",
  "High": "Høy",
  "Medium": "Middels",
  "Low": "Lav",
  "Urgent": "Haster",
  "Won": "Vunnet",
  "Lost": "Tapt",
  "Draft": "Utkast",
  "Stock In": "Varemottak",
  "Stock Out": "Vareutgang",
  "Return": "Retur",

  // Customer / Lead details tabs
  "Contacts": "Kontakter",
  "Orders": "Ordrer",
  "Stock Out History": "Vareutgangshistorikk",
  "GDPR & Privacy": "GDPR & Personvern",
  "Activity": "Aktivitet",
  "Timeline": "Tidslinje",
  "Send Email": "Send e-post",
  "Log Call": "Loggfør samtale",
  "Add Note": "Legg til notat",
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem("app_language") || "en";
  });

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem("app_language", newLang);
  };

  const t = (key) => {
    if (!key) return "";
    
    // 1. Direct dictionary match by key
    const directTranslation = translations[lang]?.[key];
    if (directTranslation) return directTranslation;

    // 2. If Norwegian mode, check phrase dictionary
    if (lang === "no") {
      const phraseMatch = phraseDictNo[key];
      if (phraseMatch) return phraseMatch;
      
      // Case-insensitive check in phrase dict
      const lowerKey = key.toString().trim().toLowerCase();
      for (const [englishPhrase, norwegianPhrase] of Object.entries(phraseDictNo)) {
        if (englishPhrase.toLowerCase() === lowerKey) {
          return norwegianPhrase;
        }
      }
    }

    // 3. Fallback to English dictionary or key itself
    return translations.en?.[key] || key;
  };

  const value = useMemo(() => ({
    lang,
    setLang: changeLanguage,
    t,
    isNo: lang === "no",
    isEn: lang === "en"
  }), [lang]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

